/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createAccount } from '../fn/account-controller/create-account';
import { CreateAccount$Params } from '../fn/account-controller/create-account';
import { listAccounts } from '../fn/account-controller/list-accounts';
import { ListAccounts$Params } from '../fn/account-controller/list-accounts';
import { listAccountTransactions } from '../fn/account-controller/list-account-transactions';
import { ListAccountTransactions$Params } from '../fn/account-controller/list-account-transactions';
import { listSelfAccounts } from '../fn/account-controller/list-self-accounts';
import { ListSelfAccounts$Params } from '../fn/account-controller/list-self-accounts';
import { listSelfAccountTransactions } from '../fn/account-controller/list-self-account-transactions';
import { ListSelfAccountTransactions$Params } from '../fn/account-controller/list-self-account-transactions';
import { payableAccount } from '../fn/account-controller/payable-account';
import { PayableAccount$Params } from '../fn/account-controller/payable-account';
import { SuccessResponseAccountDetailDto } from '../models/success-response-account-detail-dto';
import { SuccessResponseArrayAccountDetailDto } from '../models/success-response-array-account-detail-dto';
import { SuccessResponsePagedResultAccountDetailDto } from '../models/success-response-paged-result-account-detail-dto';
import { SuccessResponsePagedResultTransactionDetailDto } from '../models/success-response-paged-result-transaction-detail-dto';
import { updateAccount } from '../fn/account-controller/update-account';
import { UpdateAccount$Params } from '../fn/account-controller/update-account';
import { updateSelf } from '../fn/account-controller/update-self';
import { UpdateSelf$Params } from '../fn/account-controller/update-self';

@Injectable({ providedIn: 'root' })
export class AccountControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createAccount()` */
  static readonly CreateAccountPath = '/api/account/create';

  /**
   * Create new account.
   *
   * Authorities : 'create:account'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAccount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAccount$Response(params: CreateAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseAccountDetailDto>> {
    return createAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new account.
   *
   * Authorities : 'create:account'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAccount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAccount(params: CreateAccount$Params, context?: HttpContext): Observable<SuccessResponseAccountDetailDto> {
    return this.createAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseAccountDetailDto>): SuccessResponseAccountDetailDto => r.body)
    );
  }

  /** Path part for operation `updateAccount()` */
  static readonly UpdateAccountPath = '/api/account/{id}/update';

  /**
   * Update account details.
   *
   * Authorities : 'update:account'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAccount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAccount$Response(params: UpdateAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseAccountDetailDto>> {
    return updateAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * Update account details.
   *
   * Authorities : 'update:account'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAccount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAccount(params: UpdateAccount$Params, context?: HttpContext): Observable<SuccessResponseAccountDetailDto> {
    return this.updateAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseAccountDetailDto>): SuccessResponseAccountDetailDto => r.body)
    );
  }

  /** Path part for operation `updateSelf()` */
  static readonly UpdateSelfPath = '/api/account/{id}/update/me';

  /**
   * Update own account details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSelf()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSelf$Response(params: UpdateSelf$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseAccountDetailDto>> {
    return updateSelf(this.http, this.rootUrl, params, context);
  }

  /**
   * Update own account details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSelf$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSelf(params: UpdateSelf$Params, context?: HttpContext): Observable<SuccessResponseAccountDetailDto> {
    return this.updateSelf$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseAccountDetailDto>): SuccessResponseAccountDetailDto => r.body)
    );
  }

  /** Path part for operation `listAccounts()` */
  static readonly ListAccountsPath = '/api/account/list';

  /**
   * List all accounts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAccounts()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAccounts$Response(params: ListAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultAccountDetailDto>> {
    return listAccounts(this.http, this.rootUrl, params, context);
  }

  /**
   * List all accounts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAccounts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAccounts(params: ListAccounts$Params, context?: HttpContext): Observable<SuccessResponsePagedResultAccountDetailDto> {
    return this.listAccounts$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultAccountDetailDto>): SuccessResponsePagedResultAccountDetailDto => r.body)
    );
  }

  /** Path part for operation `listSelfAccounts()` */
  static readonly ListSelfAccountsPath = '/api/account/list/me';

  /**
   * List own accounts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listSelfAccounts()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfAccounts$Response(params: ListSelfAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultAccountDetailDto>> {
    return listSelfAccounts(this.http, this.rootUrl, params, context);
  }

  /**
   * List own accounts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listSelfAccounts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfAccounts(params: ListSelfAccounts$Params, context?: HttpContext): Observable<SuccessResponsePagedResultAccountDetailDto> {
    return this.listSelfAccounts$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultAccountDetailDto>): SuccessResponsePagedResultAccountDetailDto => r.body)
    );
  }

  /** Path part for operation `listAccountTransactions()` */
  static readonly ListAccountTransactionsPath = '/api/account/{id}/transactions';

  /**
   * List transactions for account.
   *
   * Authorities : 'read:transactions'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAccountTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAccountTransactions$Response(params: ListAccountTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultTransactionDetailDto>> {
    return listAccountTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * List transactions for account.
   *
   * Authorities : 'read:transactions'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAccountTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAccountTransactions(params: ListAccountTransactions$Params, context?: HttpContext): Observable<SuccessResponsePagedResultTransactionDetailDto> {
    return this.listAccountTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultTransactionDetailDto>): SuccessResponsePagedResultTransactionDetailDto => r.body)
    );
  }

  /** Path part for operation `listSelfAccountTransactions()` */
  static readonly ListSelfAccountTransactionsPath = '/api/account/{id}/transactions/me';

  /**
   * List own transactions for account.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listSelfAccountTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfAccountTransactions$Response(params: ListSelfAccountTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultTransactionDetailDto>> {
    return listSelfAccountTransactions(this.http, this.rootUrl, params, context);
  }

  /**
   * List own transactions for account.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listSelfAccountTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfAccountTransactions(params: ListSelfAccountTransactions$Params, context?: HttpContext): Observable<SuccessResponsePagedResultTransactionDetailDto> {
    return this.listSelfAccountTransactions$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultTransactionDetailDto>): SuccessResponsePagedResultTransactionDetailDto => r.body)
    );
  }

  /** Path part for operation `payableAccount()` */
  static readonly PayableAccountPath = '/api/account/payable-account';

  /**
   * Get account data for payable.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `payableAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  payableAccount$Response(params?: PayableAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayAccountDetailDto>> {
    return payableAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * Get account data for payable.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `payableAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  payableAccount(params?: PayableAccount$Params, context?: HttpContext): Observable<SuccessResponseArrayAccountDetailDto> {
    return this.payableAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayAccountDetailDto>): SuccessResponseArrayAccountDetailDto => r.body)
    );
  }

}
