/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { generateApiKey } from '../fn/api-key-controller/generate-api-key';
import { GenerateApiKey$Params } from '../fn/api-key-controller/generate-api-key';
import { listApiKeys } from '../fn/api-key-controller/list-api-keys';
import { ListApiKeys$Params } from '../fn/api-key-controller/list-api-keys';
import { listApiScopes } from '../fn/api-key-controller/list-api-scopes';
import { ListApiScopes$Params } from '../fn/api-key-controller/list-api-scopes';
import { revokeApiKey } from '../fn/api-key-controller/revoke-api-key';
import { RevokeApiKey$Params } from '../fn/api-key-controller/revoke-api-key';
import { SuccessResponseApiKeyDto } from '../models/success-response-api-key-dto';
import { SuccessResponseArrayApiKeyDto } from '../models/success-response-array-api-key-dto';
import { SuccessResponseArrayString } from '../models/success-response-array-string';
import { SuccessResponseBoolean } from '../models/success-response-boolean';
import { updateApiKeyPermissions } from '../fn/api-key-controller/update-api-key-permissions';
import { UpdateApiKeyPermissions$Params } from '../fn/api-key-controller/update-api-key-permissions';

@Injectable({ providedIn: 'root' })
export class ApiKeyControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `generateApiKey()` */
  static readonly GenerateApiKeyPath = '/api/auth/apikey/generate';

  /**
   * Generate API Key.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateApiKey()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateApiKey$Response(params: GenerateApiKey$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseApiKeyDto>> {
    return generateApiKey(this.http, this.rootUrl, params, context);
  }

  /**
   * Generate API Key.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateApiKey$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateApiKey(params: GenerateApiKey$Params, context?: HttpContext): Observable<SuccessResponseApiKeyDto> {
    return this.generateApiKey$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseApiKeyDto>): SuccessResponseApiKeyDto => r.body)
    );
  }

  /** Path part for operation `listApiKeys()` */
  static readonly ListApiKeysPath = '/api/auth/apikey/list';

  /**
   * List all API keys.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listApiKeys()` instead.
   *
   * This method doesn't expect any request body.
   */
  listApiKeys$Response(params?: ListApiKeys$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayApiKeyDto>> {
    return listApiKeys(this.http, this.rootUrl, params, context);
  }

  /**
   * List all API keys.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listApiKeys$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listApiKeys(params?: ListApiKeys$Params, context?: HttpContext): Observable<SuccessResponseArrayApiKeyDto> {
    return this.listApiKeys$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayApiKeyDto>): SuccessResponseArrayApiKeyDto => r.body)
    );
  }

  /** Path part for operation `listApiScopes()` */
  static readonly ListApiScopesPath = '/api/auth/apikey/scopes';

  /**
   * List all API scopes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listApiScopes()` instead.
   *
   * This method doesn't expect any request body.
   */
  listApiScopes$Response(params?: ListApiScopes$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayString>> {
    return listApiScopes(this.http, this.rootUrl, params, context);
  }

  /**
   * List all API scopes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listApiScopes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listApiScopes(params?: ListApiScopes$Params, context?: HttpContext): Observable<SuccessResponseArrayString> {
    return this.listApiScopes$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayString>): SuccessResponseArrayString => r.body)
    );
  }

  /** Path part for operation `updateApiKeyPermissions()` */
  static readonly UpdateApiKeyPermissionsPath = '/api/auth/apikey/permissions/{id}';

  /**
   * Update API key permissions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateApiKeyPermissions()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateApiKeyPermissions$Response(params: UpdateApiKeyPermissions$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseApiKeyDto>> {
    return updateApiKeyPermissions(this.http, this.rootUrl, params, context);
  }

  /**
   * Update API key permissions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateApiKeyPermissions$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateApiKeyPermissions(params: UpdateApiKeyPermissions$Params, context?: HttpContext): Observable<SuccessResponseApiKeyDto> {
    return this.updateApiKeyPermissions$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseApiKeyDto>): SuccessResponseApiKeyDto => r.body)
    );
  }

  /** Path part for operation `revokeApiKey()` */
  static readonly RevokeApiKeyPath = '/api/auth/apikey/revoke/{id}';

  /**
   * Revoke API key.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `revokeApiKey()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeApiKey$Response(params: RevokeApiKey$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseBoolean>> {
    return revokeApiKey(this.http, this.rootUrl, params, context);
  }

  /**
   * Revoke API key.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `revokeApiKey$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeApiKey(params: RevokeApiKey$Params, context?: HttpContext): Observable<SuccessResponseBoolean> {
    return this.revokeApiKey$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseBoolean>): SuccessResponseBoolean => r.body)
    );
  }

}
