/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { executeCron } from '../fn/cron-controller/execute-cron';
import { ExecuteCron$Params } from '../fn/cron-controller/execute-cron';
import { getCronLogs } from '../fn/cron-controller/get-cron-logs';
import { GetCronLogs$Params } from '../fn/cron-controller/get-cron-logs';
import { getScheduledJobs } from '../fn/cron-controller/get-scheduled-jobs';
import { GetScheduledJobs$Params } from '../fn/cron-controller/get-scheduled-jobs';
import { runScheduledJob } from '../fn/cron-controller/run-scheduled-job';
import { RunScheduledJob$Params } from '../fn/cron-controller/run-scheduled-job';
import { SuccessResponseArrayCronJobDto } from '../models/success-response-array-cron-job-dto';
import { SuccessResponseArraySuccessResponse } from '../models/success-response-array-success-response';
import { SuccessResponseSuccessResponse } from '../models/success-response-success-response';

@Injectable({ providedIn: 'root' })
export class CronControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `executeCron()` */
  static readonly ExecuteCronPath = '/api/cron/trigger';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `executeCron()` instead.
   *
   * This method doesn't expect any request body.
   */
  executeCron$Response(params: ExecuteCron$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return executeCron(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `executeCron$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  executeCron(params: ExecuteCron$Params, context?: HttpContext): Observable<void> {
    return this.executeCron$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `runScheduledJob()` */
  static readonly RunScheduledJobPath = '/api/cron/run/{name}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `runScheduledJob()` instead.
   *
   * This method doesn't expect any request body.
   */
  runScheduledJob$Response(params: RunScheduledJob$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseSuccessResponse>> {
    return runScheduledJob(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `runScheduledJob$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  runScheduledJob(params: RunScheduledJob$Params, context?: HttpContext): Observable<SuccessResponseSuccessResponse> {
    return this.runScheduledJob$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseSuccessResponse>): SuccessResponseSuccessResponse => r.body)
    );
  }

  /** Path part for operation `getScheduledJobs()` */
  static readonly GetScheduledJobsPath = '/api/cron/jobs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getScheduledJobs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getScheduledJobs$Response(params?: GetScheduledJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayCronJobDto>> {
    return getScheduledJobs(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getScheduledJobs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getScheduledJobs(params?: GetScheduledJobs$Params, context?: HttpContext): Observable<SuccessResponseArrayCronJobDto> {
    return this.getScheduledJobs$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayCronJobDto>): SuccessResponseArrayCronJobDto => r.body)
    );
  }

  /** Path part for operation `getCronLogs()` */
  static readonly GetCronLogsPath = '/api/cron/logs/{name}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCronLogs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCronLogs$Response(params: GetCronLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArraySuccessResponse>> {
    return getCronLogs(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCronLogs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCronLogs(params: GetCronLogs$Params, context?: HttpContext): Observable<SuccessResponseArraySuccessResponse> {
    return this.getCronLogs$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArraySuccessResponse>): SuccessResponseArraySuccessResponse => r.body)
    );
  }

}
