/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { donationControllerCreateOneTime } from '../fn/donations/donation-controller-create-one-time';
import { DonationControllerCreateOneTime$Params } from '../fn/donations/donation-controller-create-one-time';
import { donationControllerCreateRegular } from '../fn/donations/donation-controller-create-regular';
import { DonationControllerCreateRegular$Params } from '../fn/donations/donation-controller-create-regular';
import { donationControllerProcessPayment } from '../fn/donations/donation-controller-process-payment';
import { DonationControllerProcessPayment$Params } from '../fn/donations/donation-controller-process-payment';
import { DonationDto } from '../models/donation-dto';
import { SuccessResponse } from '../models/success-response';

@Injectable({ providedIn: 'root' })
export class DonationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `donationControllerCreateRegular()` */
  static readonly DonationControllerCreateRegularPath = '/api/finance/donations/regular';

  /**
   * Create a regular donation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `donationControllerCreateRegular()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  donationControllerCreateRegular$Response(params: DonationControllerCreateRegular$Params, context?: HttpContext): Observable<StrictHttpResponse<DonationDto>> {
    return donationControllerCreateRegular(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a regular donation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `donationControllerCreateRegular$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  donationControllerCreateRegular(params: DonationControllerCreateRegular$Params, context?: HttpContext): Observable<DonationDto> {
    return this.donationControllerCreateRegular$Response(params, context).pipe(
      map((r: StrictHttpResponse<DonationDto>): DonationDto => r.body)
    );
  }

  /** Path part for operation `donationControllerCreateOneTime()` */
  static readonly DonationControllerCreateOneTimePath = '/api/finance/donations/one-time';

  /**
   * Create a one-time donation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `donationControllerCreateOneTime()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  donationControllerCreateOneTime$Response(params: DonationControllerCreateOneTime$Params, context?: HttpContext): Observable<StrictHttpResponse<DonationDto>> {
    return donationControllerCreateOneTime(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a one-time donation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `donationControllerCreateOneTime$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  donationControllerCreateOneTime(params: DonationControllerCreateOneTime$Params, context?: HttpContext): Observable<DonationDto> {
    return this.donationControllerCreateOneTime$Response(params, context).pipe(
      map((r: StrictHttpResponse<DonationDto>): DonationDto => r.body)
    );
  }

  /** Path part for operation `donationControllerProcessPayment()` */
  static readonly DonationControllerProcessPaymentPath = '/api/finance/donations/{id}/process-payment';

  /**
   * Process payment for a donation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `donationControllerProcessPayment()` instead.
   *
   * This method doesn't expect any request body.
   */
  donationControllerProcessPayment$Response(params: DonationControllerProcessPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponse & {
'responsePayload'?: string;
}>> {
    return donationControllerProcessPayment(this.http, this.rootUrl, params, context);
  }

  /**
   * Process payment for a donation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `donationControllerProcessPayment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  donationControllerProcessPayment(params: DonationControllerProcessPayment$Params, context?: HttpContext): Observable<SuccessResponse & {
'responsePayload'?: string;
}> {
    return this.donationControllerProcessPayment$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponse & {
'responsePayload'?: string;
}>): SuccessResponse & {
'responsePayload'?: string;
} => r.body)
    );
  }

}
