/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createExpense } from '../fn/expense-controller/create-expense';
import { CreateExpense$Params } from '../fn/expense-controller/create-expense';
import { finalizeExpense } from '../fn/expense-controller/finalize-expense';
import { FinalizeExpense$Params } from '../fn/expense-controller/finalize-expense';
import { getExpenseById } from '../fn/expense-controller/get-expense-by-id';
import { GetExpenseById$Params } from '../fn/expense-controller/get-expense-by-id';
import { listExpenses } from '../fn/expense-controller/list-expenses';
import { ListExpenses$Params } from '../fn/expense-controller/list-expenses';
import { listSelfExpenses } from '../fn/expense-controller/list-self-expenses';
import { ListSelfExpenses$Params } from '../fn/expense-controller/list-self-expenses';
import { settleExpense } from '../fn/expense-controller/settle-expense';
import { SettleExpense$Params } from '../fn/expense-controller/settle-expense';
import { SuccessResponseExpenseDetailDto } from '../models/success-response-expense-detail-dto';
import { SuccessResponsePagedResultExpenseDetailDto } from '../models/success-response-paged-result-expense-detail-dto';
import { updateExpense } from '../fn/expense-controller/update-expense';
import { UpdateExpense$Params } from '../fn/expense-controller/update-expense';

@Injectable({ providedIn: 'root' })
export class ExpenseControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createExpense()` */
  static readonly CreateExpensePath = '/api/expense/create';

  /**
   * Create new expense.
   *
   * Authorities : 'create:expense'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createExpense()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createExpense$Response(params: CreateExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseExpenseDetailDto>> {
    return createExpense(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new expense.
   *
   * Authorities : 'create:expense'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createExpense$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createExpense(params: CreateExpense$Params, context?: HttpContext): Observable<SuccessResponseExpenseDetailDto> {
    return this.createExpense$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseExpenseDetailDto>): SuccessResponseExpenseDetailDto => r.body)
    );
  }

  /** Path part for operation `updateExpense()` */
  static readonly UpdateExpensePath = '/api/expense/{id}/update';

  /**
   * Update expense details.
   *
   * Authorities : 'update:expense'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateExpense()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExpense$Response(params: UpdateExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseExpenseDetailDto>> {
    return updateExpense(this.http, this.rootUrl, params, context);
  }

  /**
   * Update expense details.
   *
   * Authorities : 'update:expense'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateExpense$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExpense(params: UpdateExpense$Params, context?: HttpContext): Observable<SuccessResponseExpenseDetailDto> {
    return this.updateExpense$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseExpenseDetailDto>): SuccessResponseExpenseDetailDto => r.body)
    );
  }

  /** Path part for operation `finalizeExpense()` */
  static readonly FinalizeExpensePath = '/api/expense/{id}/finalize';

  /**
   * Finalize expense.
   *
   * Authorities : 'create:expense_final'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `finalizeExpense()` instead.
   *
   * This method doesn't expect any request body.
   */
  finalizeExpense$Response(params: FinalizeExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseExpenseDetailDto>> {
    return finalizeExpense(this.http, this.rootUrl, params, context);
  }

  /**
   * Finalize expense.
   *
   * Authorities : 'create:expense_final'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `finalizeExpense$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  finalizeExpense(params: FinalizeExpense$Params, context?: HttpContext): Observable<SuccessResponseExpenseDetailDto> {
    return this.finalizeExpense$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseExpenseDetailDto>): SuccessResponseExpenseDetailDto => r.body)
    );
  }

  /** Path part for operation `settleExpense()` */
  static readonly SettleExpensePath = '/api/expense/{id}/settle';

  /**
   * Settle expense.
   *
   * Authorities : 'create:expense_settle'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settleExpense()` instead.
   *
   * This method doesn't expect any request body.
   */
  settleExpense$Response(params: SettleExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseExpenseDetailDto>> {
    return settleExpense(this.http, this.rootUrl, params, context);
  }

  /**
   * Settle expense.
   *
   * Authorities : 'create:expense_settle'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settleExpense$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settleExpense(params: SettleExpense$Params, context?: HttpContext): Observable<SuccessResponseExpenseDetailDto> {
    return this.settleExpense$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseExpenseDetailDto>): SuccessResponseExpenseDetailDto => r.body)
    );
  }

  /** Path part for operation `listExpenses()` */
  static readonly ListExpensesPath = '/api/expense/list';

  /**
   * List all expenses.
   *
   * Authorities : 'read:expense'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listExpenses()` instead.
   *
   * This method doesn't expect any request body.
   */
  listExpenses$Response(params: ListExpenses$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultExpenseDetailDto>> {
    return listExpenses(this.http, this.rootUrl, params, context);
  }

  /**
   * List all expenses.
   *
   * Authorities : 'read:expense'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listExpenses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listExpenses(params: ListExpenses$Params, context?: HttpContext): Observable<SuccessResponsePagedResultExpenseDetailDto> {
    return this.listExpenses$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultExpenseDetailDto>): SuccessResponsePagedResultExpenseDetailDto => r.body)
    );
  }

  /** Path part for operation `listSelfExpenses()` */
  static readonly ListSelfExpensesPath = '/api/expense/list/me';

  /**
   * List own expenses.
   *
   * Authorities : 'read:expense'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listSelfExpenses()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfExpenses$Response(params: ListSelfExpenses$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultExpenseDetailDto>> {
    return listSelfExpenses(this.http, this.rootUrl, params, context);
  }

  /**
   * List own expenses.
   *
   * Authorities : 'read:expense'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listSelfExpenses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfExpenses(params: ListSelfExpenses$Params, context?: HttpContext): Observable<SuccessResponsePagedResultExpenseDetailDto> {
    return this.listSelfExpenses$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultExpenseDetailDto>): SuccessResponsePagedResultExpenseDetailDto => r.body)
    );
  }

  /** Path part for operation `getExpenseById()` */
  static readonly GetExpenseByIdPath = '/api/expense/{id}';

  /**
   * Get expense by ID.
   *
   * Authorities : 'read:expense'
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getExpenseById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getExpenseById$Response(params: GetExpenseById$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseExpenseDetailDto>> {
    return getExpenseById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get expense by ID.
   *
   * Authorities : 'read:expense'
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getExpenseById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getExpenseById(params: GetExpenseById$Params, context?: HttpContext): Observable<SuccessResponseExpenseDetailDto> {
    return this.getExpenseById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseExpenseDetailDto>): SuccessResponseExpenseDetailDto => r.body)
    );
  }

}
