/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { generateReport } from '../fn/finance-report-controller/generate-report';
import { GenerateReport$Params } from '../fn/finance-report-controller/generate-report';
import { getReportList } from '../fn/finance-report-controller/get-report-list';
import { GetReportList$Params } from '../fn/finance-report-controller/get-report-list';
import { SuccessResponseArrayKeyValueDto } from '../models/success-response-array-key-value-dto';

@Injectable({ providedIn: 'root' })
export class FinanceReportControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getReportList()` */
  static readonly GetReportListPath = '/api/finance-report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReportList()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportList$Response(params?: GetReportList$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayKeyValueDto>> {
    return getReportList(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReportList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportList(params?: GetReportList$Params, context?: HttpContext): Observable<SuccessResponseArrayKeyValueDto> {
    return this.getReportList$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayKeyValueDto>): SuccessResponseArrayKeyValueDto => r.body)
    );
  }

  /** Path part for operation `generateReport()` */
  static readonly GenerateReportPath = '/api/finance-report/generate/{reportName}';

  /**
   * Download a document file.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateReport$Response(params: GenerateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return generateReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Download a document file.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateReport(params: GenerateReport$Params, context?: HttpContext): Observable<Blob> {
    return this.generateReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
