/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { healthControllerHealth } from '../fn/health/health-controller-health';
import { HealthControllerHealth$Params } from '../fn/health/health-controller-health';

@Injectable({ providedIn: 'root' })
export class HealthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `healthControllerHealth()` */
  static readonly HealthControllerHealthPath = '/api/health';

  /**
   * Health check endpoint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthControllerHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthControllerHealth$Response(params?: HealthControllerHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return healthControllerHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * Health check endpoint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthControllerHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthControllerHealth(params?: HealthControllerHealth$Params, context?: HttpContext): Observable<void> {
    return this.healthControllerHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
