/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { jobMonitoringControllerCleanOldJobs } from '../fn/job-monitoring/job-monitoring-controller-clean-old-jobs';
import { JobMonitoringControllerCleanOldJobs$Params } from '../fn/job-monitoring/job-monitoring-controller-clean-old-jobs';
import { jobMonitoringControllerGetFailedJobs } from '../fn/job-monitoring/job-monitoring-controller-get-failed-jobs';
import { JobMonitoringControllerGetFailedJobs$Params } from '../fn/job-monitoring/job-monitoring-controller-get-failed-jobs';
import { jobMonitoringControllerGetJobDetails } from '../fn/job-monitoring/job-monitoring-controller-get-job-details';
import { JobMonitoringControllerGetJobDetails$Params } from '../fn/job-monitoring/job-monitoring-controller-get-job-details';
import { jobMonitoringControllerGetJobMetrics } from '../fn/job-monitoring/job-monitoring-controller-get-job-metrics';
import { JobMonitoringControllerGetJobMetrics$Params } from '../fn/job-monitoring/job-monitoring-controller-get-job-metrics';
import { jobMonitoringControllerGetJobMetricsByName } from '../fn/job-monitoring/job-monitoring-controller-get-job-metrics-by-name';
import { JobMonitoringControllerGetJobMetricsByName$Params } from '../fn/job-monitoring/job-monitoring-controller-get-job-metrics-by-name';
import { jobMonitoringControllerGetJobPerformanceMetrics } from '../fn/job-monitoring/job-monitoring-controller-get-job-performance-metrics';
import { JobMonitoringControllerGetJobPerformanceMetrics$Params } from '../fn/job-monitoring/job-monitoring-controller-get-job-performance-metrics';
import { jobMonitoringControllerGetQueueHealth } from '../fn/job-monitoring/job-monitoring-controller-get-queue-health';
import { JobMonitoringControllerGetQueueHealth$Params } from '../fn/job-monitoring/job-monitoring-controller-get-queue-health';
import { jobMonitoringControllerGetQueueStatistics } from '../fn/job-monitoring/job-monitoring-controller-get-queue-statistics';
import { JobMonitoringControllerGetQueueStatistics$Params } from '../fn/job-monitoring/job-monitoring-controller-get-queue-statistics';
import { jobMonitoringControllerGetTtlConfig } from '../fn/job-monitoring/job-monitoring-controller-get-ttl-config';
import { JobMonitoringControllerGetTtlConfig$Params } from '../fn/job-monitoring/job-monitoring-controller-get-ttl-config';
import { jobMonitoringControllerPauseQueue } from '../fn/job-monitoring/job-monitoring-controller-pause-queue';
import { JobMonitoringControllerPauseQueue$Params } from '../fn/job-monitoring/job-monitoring-controller-pause-queue';
import { jobMonitoringControllerRemoveJob } from '../fn/job-monitoring/job-monitoring-controller-remove-job';
import { JobMonitoringControllerRemoveJob$Params } from '../fn/job-monitoring/job-monitoring-controller-remove-job';
import { jobMonitoringControllerResumeQueue } from '../fn/job-monitoring/job-monitoring-controller-resume-queue';
import { JobMonitoringControllerResumeQueue$Params } from '../fn/job-monitoring/job-monitoring-controller-resume-queue';

@Injectable({ providedIn: 'root' })
export class JobMonitoringService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `jobMonitoringControllerGetJobMetrics()` */
  static readonly JobMonitoringControllerGetJobMetricsPath = '/api/jobs/metrics';

  /**
   * Get job metrics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetJobMetrics()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobMetrics$Response(params?: JobMonitoringControllerGetJobMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetJobMetrics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job metrics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetJobMetrics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobMetrics(params?: JobMonitoringControllerGetJobMetrics$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetJobMetrics$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerGetJobMetricsByName()` */
  static readonly JobMonitoringControllerGetJobMetricsByNamePath = '/api/jobs/metrics/{jobName}';

  /**
   * Get job metrics by name.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetJobMetricsByName()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobMetricsByName$Response(params: JobMonitoringControllerGetJobMetricsByName$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetJobMetricsByName(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job metrics by name.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetJobMetricsByName$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobMetricsByName(params: JobMonitoringControllerGetJobMetricsByName$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetJobMetricsByName$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerGetJobPerformanceMetrics()` */
  static readonly JobMonitoringControllerGetJobPerformanceMetricsPath = '/api/jobs/performance';

  /**
   * Get job performance metrics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetJobPerformanceMetrics()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobPerformanceMetrics$Response(params?: JobMonitoringControllerGetJobPerformanceMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetJobPerformanceMetrics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job performance metrics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetJobPerformanceMetrics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobPerformanceMetrics(params?: JobMonitoringControllerGetJobPerformanceMetrics$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetJobPerformanceMetrics$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerGetFailedJobs()` */
  static readonly JobMonitoringControllerGetFailedJobsPath = '/api/jobs/failed';

  /**
   * Get failed jobs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetFailedJobs()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetFailedJobs$Response(params?: JobMonitoringControllerGetFailedJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetFailedJobs(this.http, this.rootUrl, params, context);
  }

  /**
   * Get failed jobs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetFailedJobs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetFailedJobs(params?: JobMonitoringControllerGetFailedJobs$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetFailedJobs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerGetJobDetails()` */
  static readonly JobMonitoringControllerGetJobDetailsPath = '/api/jobs/details/{jobId}';

  /**
   * Get job details by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetJobDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobDetails$Response(params: JobMonitoringControllerGetJobDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetJobDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job details by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetJobDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetJobDetails(params: JobMonitoringControllerGetJobDetails$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetJobDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerGetQueueHealth()` */
  static readonly JobMonitoringControllerGetQueueHealthPath = '/api/jobs/health';

  /**
   * Get queue health status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetQueueHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetQueueHealth$Response(params?: JobMonitoringControllerGetQueueHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetQueueHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * Get queue health status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetQueueHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetQueueHealth(params?: JobMonitoringControllerGetQueueHealth$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetQueueHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerGetQueueStatistics()` */
  static readonly JobMonitoringControllerGetQueueStatisticsPath = '/api/jobs/statistics';

  /**
   * Get comprehensive queue statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetQueueStatistics()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetQueueStatistics$Response(params?: JobMonitoringControllerGetQueueStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetQueueStatistics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get comprehensive queue statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetQueueStatistics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetQueueStatistics(params?: JobMonitoringControllerGetQueueStatistics$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetQueueStatistics$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerCleanOldJobs()` */
  static readonly JobMonitoringControllerCleanOldJobsPath = '/api/jobs/clean';

  /**
   * Clean old jobs (manual cleanup - TTL handles automatic cleanup).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerCleanOldJobs()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerCleanOldJobs$Response(params?: JobMonitoringControllerCleanOldJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerCleanOldJobs(this.http, this.rootUrl, params, context);
  }

  /**
   * Clean old jobs (manual cleanup - TTL handles automatic cleanup).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerCleanOldJobs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerCleanOldJobs(params?: JobMonitoringControllerCleanOldJobs$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerCleanOldJobs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerPauseQueue()` */
  static readonly JobMonitoringControllerPauseQueuePath = '/api/jobs/pause';

  /**
   * Pause the queue.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerPauseQueue()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerPauseQueue$Response(params?: JobMonitoringControllerPauseQueue$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerPauseQueue(this.http, this.rootUrl, params, context);
  }

  /**
   * Pause the queue.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerPauseQueue$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerPauseQueue(params?: JobMonitoringControllerPauseQueue$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerPauseQueue$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerResumeQueue()` */
  static readonly JobMonitoringControllerResumeQueuePath = '/api/jobs/resume';

  /**
   * Resume the queue.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerResumeQueue()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerResumeQueue$Response(params?: JobMonitoringControllerResumeQueue$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerResumeQueue(this.http, this.rootUrl, params, context);
  }

  /**
   * Resume the queue.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerResumeQueue$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerResumeQueue(params?: JobMonitoringControllerResumeQueue$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerResumeQueue$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerRemoveJob()` */
  static readonly JobMonitoringControllerRemoveJobPath = '/api/jobs/{jobId}';

  /**
   * Remove a job.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerRemoveJob()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerRemoveJob$Response(params: JobMonitoringControllerRemoveJob$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerRemoveJob(this.http, this.rootUrl, params, context);
  }

  /**
   * Remove a job.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerRemoveJob$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerRemoveJob(params: JobMonitoringControllerRemoveJob$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerRemoveJob$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `jobMonitoringControllerGetTtlConfig()` */
  static readonly JobMonitoringControllerGetTtlConfigPath = '/api/jobs/ttl/config';

  /**
   * Get TTL configuration for job cleanup.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `jobMonitoringControllerGetTtlConfig()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetTtlConfig$Response(params?: JobMonitoringControllerGetTtlConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return jobMonitoringControllerGetTtlConfig(this.http, this.rootUrl, params, context);
  }

  /**
   * Get TTL configuration for job cleanup.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `jobMonitoringControllerGetTtlConfig$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  jobMonitoringControllerGetTtlConfig(params?: JobMonitoringControllerGetTtlConfig$Params, context?: HttpContext): Observable<void> {
    return this.jobMonitoringControllerGetTtlConfig$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
