/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { cleanOldJobs } from '../fn/job-monitoring-controller/clean-old-jobs';
import { CleanOldJobs$Params } from '../fn/job-monitoring-controller/clean-old-jobs';
import { getFailedJobs } from '../fn/job-monitoring-controller/get-failed-jobs';
import { GetFailedJobs$Params } from '../fn/job-monitoring-controller/get-failed-jobs';
import { getJobDetails } from '../fn/job-monitoring-controller/get-job-details';
import { GetJobDetails$Params } from '../fn/job-monitoring-controller/get-job-details';
import { getJobMetrics } from '../fn/job-monitoring-controller/get-job-metrics';
import { GetJobMetrics$Params } from '../fn/job-monitoring-controller/get-job-metrics';
import { getJobMetricsByName } from '../fn/job-monitoring-controller/get-job-metrics-by-name';
import { GetJobMetricsByName$Params } from '../fn/job-monitoring-controller/get-job-metrics-by-name';
import { getJobPerformanceMetrics } from '../fn/job-monitoring-controller/get-job-performance-metrics';
import { GetJobPerformanceMetrics$Params } from '../fn/job-monitoring-controller/get-job-performance-metrics';
import { getQueueStatistics } from '../fn/job-monitoring-controller/get-queue-statistics';
import { GetQueueStatistics$Params } from '../fn/job-monitoring-controller/get-queue-statistics';
import { pauseQueue } from '../fn/job-monitoring-controller/pause-queue';
import { PauseQueue$Params } from '../fn/job-monitoring-controller/pause-queue';
import { removeJob } from '../fn/job-monitoring-controller/remove-job';
import { RemoveJob$Params } from '../fn/job-monitoring-controller/remove-job';
import { retryAllFailedJobs } from '../fn/job-monitoring-controller/retry-all-failed-jobs';
import { RetryAllFailedJobs$Params } from '../fn/job-monitoring-controller/retry-all-failed-jobs';
import { retryJob } from '../fn/job-monitoring-controller/retry-job';
import { RetryJob$Params } from '../fn/job-monitoring-controller/retry-job';

@Injectable({ providedIn: 'root' })
export class JobMonitoringControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getJobMetrics()` */
  static readonly GetJobMetricsPath = '/api/jobs/metrics';

  /**
   * Get job metrics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJobMetrics()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobMetrics$Response(params?: GetJobMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return getJobMetrics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job metrics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJobMetrics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobMetrics(params?: GetJobMetrics$Params, context?: HttpContext): Observable<void> {
    return this.getJobMetrics$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getJobMetricsByName()` */
  static readonly GetJobMetricsByNamePath = '/api/jobs/metrics/{jobName}';

  /**
   * Get job metrics by name.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJobMetricsByName()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobMetricsByName$Response(params: GetJobMetricsByName$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return getJobMetricsByName(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job metrics by name.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJobMetricsByName$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobMetricsByName(params: GetJobMetricsByName$Params, context?: HttpContext): Observable<void> {
    return this.getJobMetricsByName$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getJobPerformanceMetrics()` */
  static readonly GetJobPerformanceMetricsPath = '/api/jobs/performance';

  /**
   * Get job performance metrics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJobPerformanceMetrics()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobPerformanceMetrics$Response(params?: GetJobPerformanceMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return getJobPerformanceMetrics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job performance metrics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJobPerformanceMetrics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobPerformanceMetrics(params?: GetJobPerformanceMetrics$Params, context?: HttpContext): Observable<void> {
    return this.getJobPerformanceMetrics$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getFailedJobs()` */
  static readonly GetFailedJobsPath = '/api/jobs/failed';

  /**
   * Get failed jobs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFailedJobs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFailedJobs$Response(params?: GetFailedJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return getFailedJobs(this.http, this.rootUrl, params, context);
  }

  /**
   * Get failed jobs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFailedJobs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFailedJobs(params?: GetFailedJobs$Params, context?: HttpContext): Observable<void> {
    return this.getFailedJobs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getJobDetails()` */
  static readonly GetJobDetailsPath = '/api/jobs/details/{jobId}';

  /**
   * Get job details by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJobDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobDetails$Response(params: GetJobDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return getJobDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Get job details by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJobDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJobDetails(params: GetJobDetails$Params, context?: HttpContext): Observable<void> {
    return this.getJobDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getQueueStatistics()` */
  static readonly GetQueueStatisticsPath = '/api/jobs/statistics';

  /**
   * Get comprehensive queue statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQueueStatistics()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQueueStatistics$Response(params?: GetQueueStatistics$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return getQueueStatistics(this.http, this.rootUrl, params, context);
  }

  /**
   * Get comprehensive queue statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQueueStatistics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQueueStatistics(params?: GetQueueStatistics$Params, context?: HttpContext): Observable<void> {
    return this.getQueueStatistics$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `cleanOldJobs()` */
  static readonly CleanOldJobsPath = '/api/jobs/clean';

  /**
   * Clean old jobs (manual cleanup - TTL handles automatic cleanup).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cleanOldJobs()` instead.
   *
   * This method doesn't expect any request body.
   */
  cleanOldJobs$Response(params?: CleanOldJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return cleanOldJobs(this.http, this.rootUrl, params, context);
  }

  /**
   * Clean old jobs (manual cleanup - TTL handles automatic cleanup).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cleanOldJobs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cleanOldJobs(params?: CleanOldJobs$Params, context?: HttpContext): Observable<void> {
    return this.cleanOldJobs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `pauseQueue()` */
  static readonly PauseQueuePath = '/api/jobs/queue/{operation}';

  /**
   * Pause the queue.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `pauseQueue()` instead.
   *
   * This method doesn't expect any request body.
   */
  pauseQueue$Response(params: PauseQueue$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return pauseQueue(this.http, this.rootUrl, params, context);
  }

  /**
   * Pause the queue.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `pauseQueue$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  pauseQueue(params: PauseQueue$Params, context?: HttpContext): Observable<void> {
    return this.pauseQueue$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `removeJob()` */
  static readonly RemoveJobPath = '/api/jobs/{jobId}';

  /**
   * Remove a job.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeJob()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeJob$Response(params: RemoveJob$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removeJob(this.http, this.rootUrl, params, context);
  }

  /**
   * Remove a job.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeJob$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeJob(params: RemoveJob$Params, context?: HttpContext): Observable<void> {
    return this.removeJob$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `retryJob()` */
  static readonly RetryJobPath = '/api/jobs/retry/{jobId}';

  /**
   * Retry a failed job.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retryJob()` instead.
   *
   * This method doesn't expect any request body.
   */
  retryJob$Response(params: RetryJob$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return retryJob(this.http, this.rootUrl, params, context);
  }

  /**
   * Retry a failed job.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retryJob$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retryJob(params: RetryJob$Params, context?: HttpContext): Observable<void> {
    return this.retryJob$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `retryAllFailedJobs()` */
  static readonly RetryAllFailedJobsPath = '/api/jobs/retry-all-failed';

  /**
   * Retry all failed jobs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retryAllFailedJobs()` instead.
   *
   * This method doesn't expect any request body.
   */
  retryAllFailedJobs$Response(params?: RetryAllFailedJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return retryAllFailedJobs(this.http, this.rootUrl, params, context);
  }

  /**
   * Retry all failed jobs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retryAllFailedJobs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retryAllFailedJobs(params?: RetryAllFailedJobs$Params, context?: HttpContext): Observable<void> {
    return this.retryAllFailedJobs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
