/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAuthUrl } from '../fn/o-auth-controller/get-auth-url';
import { GetAuthUrl$Params } from '../fn/o-auth-controller/get-auth-url';
import { getProviders } from '../fn/o-auth-controller/get-providers';
import { GetProviders$Params } from '../fn/o-auth-controller/get-providers';
import { getScopes } from '../fn/o-auth-controller/get-scopes';
import { GetScopes$Params } from '../fn/o-auth-controller/get-scopes';
import { getTokens } from '../fn/o-auth-controller/get-tokens';
import { GetTokens$Params } from '../fn/o-auth-controller/get-tokens';
import { revokeTokens } from '../fn/o-auth-controller/revoke-tokens';
import { RevokeTokens$Params } from '../fn/o-auth-controller/revoke-tokens';
import { SuccessResponseArrayString } from '../models/success-response-array-string';
import { SuccessResponsePagedResultAuthTokenDto } from '../models/success-response-paged-result-auth-token-dto';
import { SuccessResponseString } from '../models/success-response-string';

@Injectable({ providedIn: 'root' })
export class OAuthControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAuthUrl()` */
  static readonly GetAuthUrlPath = '/api/auth/oauth/{provider}/auth-url';

  /**
   * Get OAuth authorization URL.
   *
   * Returns the OAuth URL to redirect users to for authentication. State parameter is automatically generated server-side for security.
   *
   * **Required Permissions:**
   * - `create:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAuthUrl()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthUrl$Response(params: GetAuthUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
    return getAuthUrl(this.http, this.rootUrl, params, context);
  }

  /**
   * Get OAuth authorization URL.
   *
   * Returns the OAuth URL to redirect users to for authentication. State parameter is automatically generated server-side for security.
   *
   * **Required Permissions:**
   * - `create:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAuthUrl$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthUrl(params: GetAuthUrl$Params, context?: HttpContext): Observable<SuccessResponseString> {
    return this.getAuthUrl$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseString>): SuccessResponseString => r.body)
    );
  }

  /** Path part for operation `getScopes()` */
  static readonly GetScopesPath = '/api/auth/oauth/{provider}/scopes';

  /**
   * Get available OAuth scopes for provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getScopes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getScopes$Response(params: GetScopes$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayString>> {
    return getScopes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get available OAuth scopes for provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getScopes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getScopes(params: GetScopes$Params, context?: HttpContext): Observable<SuccessResponseArrayString> {
    return this.getScopes$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayString>): SuccessResponseArrayString => r.body)
    );
  }

  /** Path part for operation `getTokens()` */
  static readonly GetTokensPath = '/api/auth/oauth/{provider}/tokens';

  /**
   * Get available OAuth tokens for provider.
   *
   * **Required Permissions:**
   * - `read:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTokens()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTokens$Response(params: GetTokens$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultAuthTokenDto>> {
    return getTokens(this.http, this.rootUrl, params, context);
  }

  /**
   * Get available OAuth tokens for provider.
   *
   * **Required Permissions:**
   * - `read:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTokens$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTokens(params: GetTokens$Params, context?: HttpContext): Observable<SuccessResponsePagedResultAuthTokenDto> {
    return this.getTokens$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultAuthTokenDto>): SuccessResponsePagedResultAuthTokenDto => r.body)
    );
  }

  /** Path part for operation `revokeTokens()` */
  static readonly RevokeTokensPath = '/api/auth/oauth/{provider}/tokens/{id}/revoke';

  /**
   * Revoke OAuth tokens.
   *
   * **Required Permissions:**
   * - `delete:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `revokeTokens()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeTokens$Response(params: RevokeTokens$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
    return revokeTokens(this.http, this.rootUrl, params, context);
  }

  /**
   * Revoke OAuth tokens.
   *
   * **Required Permissions:**
   * - `delete:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `revokeTokens$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeTokens(params: RevokeTokens$Params, context?: HttpContext): Observable<SuccessResponseString> {
    return this.revokeTokens$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseString>): SuccessResponseString => r.body)
    );
  }

  /** Path part for operation `getProviders()` */
  static readonly GetProvidersPath = '/api/auth/oauth/providers';

  /**
   * Get available OAuth providers.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProviders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProviders$Response(params?: GetProviders$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayString>> {
    return getProviders(this.http, this.rootUrl, params, context);
  }

  /**
   * Get available OAuth providers.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProviders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProviders(params?: GetProviders$Params, context?: HttpContext): Observable<SuccessResponseArrayString> {
    return this.getProviders$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayString>): SuccessResponseArrayString => r.body)
    );
  }

}
