/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getGmailAuthUrl } from '../fn/o-auth-controller/get-gmail-auth-url';
import { GetGmailAuthUrl$Params } from '../fn/o-auth-controller/get-gmail-auth-url';
import { getGoogleScopes } from '../fn/o-auth-controller/get-google-scopes';
import { GetGoogleScopes$Params } from '../fn/o-auth-controller/get-google-scopes';
import { getGoogleTokens } from '../fn/o-auth-controller/get-google-tokens';
import { GetGoogleTokens$Params } from '../fn/o-auth-controller/get-google-tokens';
import { revokeGoogleTokens } from '../fn/o-auth-controller/revoke-google-tokens';
import { RevokeGoogleTokens$Params } from '../fn/o-auth-controller/revoke-google-tokens';
import { SuccessResponseArrayString } from '../models/success-response-array-string';
import { SuccessResponsePagedResultAuthTokenDto } from '../models/success-response-paged-result-auth-token-dto';
import { SuccessResponseString } from '../models/success-response-string';

@Injectable({ providedIn: 'root' })
export class OAuthControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getGmailAuthUrl()` */
  static readonly GetGmailAuthUrlPath = '/api/auth/oauth/google/auth-url';

  /**
   * Get Gmail OAuth authorization URL.
   *
   * Returns the OAuth URL to redirect users to for Gmail authentication. State parameter is automatically generated server-side for security.
   *
   * **Required Permissions:**
   * - `create:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGmailAuthUrl()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGmailAuthUrl$Response(params?: GetGmailAuthUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
    return getGmailAuthUrl(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Gmail OAuth authorization URL.
   *
   * Returns the OAuth URL to redirect users to for Gmail authentication. State parameter is automatically generated server-side for security.
   *
   * **Required Permissions:**
   * - `create:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGmailAuthUrl$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGmailAuthUrl(params?: GetGmailAuthUrl$Params, context?: HttpContext): Observable<SuccessResponseString> {
    return this.getGmailAuthUrl$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseString>): SuccessResponseString => r.body)
    );
  }

  /** Path part for operation `getGoogleScopes()` */
  static readonly GetGoogleScopesPath = '/api/auth/oauth/google/scopes';

  /**
   * Get available Google OAuth scopes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGoogleScopes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGoogleScopes$Response(params?: GetGoogleScopes$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayString>> {
    return getGoogleScopes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get available Google OAuth scopes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGoogleScopes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGoogleScopes(params?: GetGoogleScopes$Params, context?: HttpContext): Observable<SuccessResponseArrayString> {
    return this.getGoogleScopes$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayString>): SuccessResponseArrayString => r.body)
    );
  }

  /** Path part for operation `getGoogleTokens()` */
  static readonly GetGoogleTokensPath = '/api/auth/oauth/tokens';

  /**
   * Get available OAuth tokens.
   *
   * **Required Permissions:**
   * - `read:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGoogleTokens()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGoogleTokens$Response(params?: GetGoogleTokens$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultAuthTokenDto>> {
    return getGoogleTokens(this.http, this.rootUrl, params, context);
  }

  /**
   * Get available OAuth tokens.
   *
   * **Required Permissions:**
   * - `read:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGoogleTokens$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGoogleTokens(params?: GetGoogleTokens$Params, context?: HttpContext): Observable<SuccessResponsePagedResultAuthTokenDto> {
    return this.getGoogleTokens$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultAuthTokenDto>): SuccessResponsePagedResultAuthTokenDto => r.body)
    );
  }

  /** Path part for operation `revokeGoogleTokens()` */
  static readonly RevokeGoogleTokensPath = '/api/auth/oauth/tokens/{id}/revoke';

  /**
   * Revoke OAuth tokens.
   *
   * **Required Permissions:**
   * - `delete:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `revokeGoogleTokens()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeGoogleTokens$Response(params: RevokeGoogleTokens$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
    return revokeGoogleTokens(this.http, this.rootUrl, params, context);
  }

  /**
   * Revoke OAuth tokens.
   *
   * **Required Permissions:**
   * - `delete:oauth_token`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `revokeGoogleTokens$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeGoogleTokens(params: RevokeGoogleTokens$Params, context?: HttpContext): Observable<SuccessResponseString> {
    return this.revokeGoogleTokens$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseString>): SuccessResponseString => r.body)
    );
  }

}
