/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { oAuthControllerGetGmailAuthUrl } from '../fn/o-auth/o-auth-controller-get-gmail-auth-url';
import { OAuthControllerGetGmailAuthUrl$Params } from '../fn/o-auth/o-auth-controller-get-gmail-auth-url';
import { oAuthControllerGetGoogleScopes } from '../fn/o-auth/o-auth-controller-get-google-scopes';
import { OAuthControllerGetGoogleScopes$Params } from '../fn/o-auth/o-auth-controller-get-google-scopes';
import { oAuthControllerHandleGmailCallback } from '../fn/o-auth/o-auth-controller-handle-gmail-callback';
import { OAuthControllerHandleGmailCallback$Params } from '../fn/o-auth/o-auth-controller-handle-gmail-callback';

@Injectable({ providedIn: 'root' })
export class OAuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `oAuthControllerGetGmailAuthUrl()` */
  static readonly OAuthControllerGetGmailAuthUrlPath = '/api/auth/oauth/google/auth-url';

  /**
   * Get Gmail OAuth authorization URL.
   *
   * Returns the OAuth URL to redirect users to for Gmail authentication
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `oAuthControllerGetGmailAuthUrl()` instead.
   *
   * This method doesn't expect any request body.
   */
  oAuthControllerGetGmailAuthUrl$Response(params: OAuthControllerGetGmailAuthUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return oAuthControllerGetGmailAuthUrl(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Gmail OAuth authorization URL.
   *
   * Returns the OAuth URL to redirect users to for Gmail authentication
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `oAuthControllerGetGmailAuthUrl$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  oAuthControllerGetGmailAuthUrl(params: OAuthControllerGetGmailAuthUrl$Params, context?: HttpContext): Observable<void> {
    return this.oAuthControllerGetGmailAuthUrl$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `oAuthControllerGetGoogleScopes()` */
  static readonly OAuthControllerGetGoogleScopesPath = '/api/auth/oauth/google/scopes';

  /**
   * Get available Google OAuth scopes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `oAuthControllerGetGoogleScopes()` instead.
   *
   * This method doesn't expect any request body.
   */
  oAuthControllerGetGoogleScopes$Response(params?: OAuthControllerGetGoogleScopes$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return oAuthControllerGetGoogleScopes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get available Google OAuth scopes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `oAuthControllerGetGoogleScopes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  oAuthControllerGetGoogleScopes(params?: OAuthControllerGetGoogleScopes$Params, context?: HttpContext): Observable<void> {
    return this.oAuthControllerGetGoogleScopes$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `oAuthControllerHandleGmailCallback()` */
  static readonly OAuthControllerHandleGmailCallbackPath = '/api/auth/oauth/google/submit-callback';

  /**
   * Handle Gmail OAuth callback.
   *
   * Processes the OAuth callback code and stores the authentication tokens. Email can be provided in body or will be fetched from Google.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `oAuthControllerHandleGmailCallback()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  oAuthControllerHandleGmailCallback$Response(params: OAuthControllerHandleGmailCallback$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return oAuthControllerHandleGmailCallback(this.http, this.rootUrl, params, context);
  }

  /**
   * Handle Gmail OAuth callback.
   *
   * Processes the OAuth callback code and stores the authentication tokens. Email can be provided in body or will be fetched from Google.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `oAuthControllerHandleGmailCallback$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  oAuthControllerHandleGmailCallback(params: OAuthControllerHandleGmailCallback$Params, context?: HttpContext): Observable<void> {
    return this.oAuthControllerHandleGmailCallback$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
