/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { publicControllerContactUs } from '../fn/public/public-controller-contact-us';
import { PublicControllerContactUs$Params } from '../fn/public/public-controller-contact-us';
import { publicControllerDonate } from '../fn/public/public-controller-donate';
import { PublicControllerDonate$Params } from '../fn/public/public-controller-donate';
import { publicControllerGetCpntent } from '../fn/public/public-controller-get-cpntent';
import { PublicControllerGetCpntent$Params } from '../fn/public/public-controller-get-cpntent';
import { publicControllerGetTeam } from '../fn/public/public-controller-get-team';
import { PublicControllerGetTeam$Params } from '../fn/public/public-controller-get-team';
import { publicControllerSignUp } from '../fn/public/public-controller-sign-up';
import { PublicControllerSignUp$Params } from '../fn/public/public-controller-sign-up';

@Injectable({ providedIn: 'root' })
export class PublicService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicControllerGetTeam()` */
  static readonly PublicControllerGetTeamPath = '/api/public/team';

  /**
   * Get team members.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicControllerGetTeam()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicControllerGetTeam$Response(params?: PublicControllerGetTeam$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
}>>> {
    return publicControllerGetTeam(this.http, this.rootUrl, params, context);
  }

  /**
   * Get team members.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicControllerGetTeam$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicControllerGetTeam(params?: PublicControllerGetTeam$Params, context?: HttpContext): Observable<Array<{
}>> {
    return this.publicControllerGetTeam$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<{
}>>): Array<{
}> => r.body)
    );
  }

  /** Path part for operation `publicControllerGetCpntent()` */
  static readonly PublicControllerGetCpntentPath = '/api/public/content';

  /**
   * Get public content.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicControllerGetCpntent()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicControllerGetCpntent$Response(params?: PublicControllerGetCpntent$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return publicControllerGetCpntent(this.http, this.rootUrl, params, context);
  }

  /**
   * Get public content.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicControllerGetCpntent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicControllerGetCpntent(params?: PublicControllerGetCpntent$Params, context?: HttpContext): Observable<{
}> {
    return this.publicControllerGetCpntent$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `publicControllerContactUs()` */
  static readonly PublicControllerContactUsPath = '/api/public/contact';

  /**
   * Submit contact form.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicControllerContactUs()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicControllerContactUs$Response(params: PublicControllerContactUs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return publicControllerContactUs(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit contact form.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicControllerContactUs$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicControllerContactUs(params: PublicControllerContactUs$Params, context?: HttpContext): Observable<void> {
    return this.publicControllerContactUs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `publicControllerSignUp()` */
  static readonly PublicControllerSignUpPath = '/api/public/signup';

  /**
   * Sign up.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicControllerSignUp()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicControllerSignUp$Response(params: PublicControllerSignUp$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return publicControllerSignUp(this.http, this.rootUrl, params, context);
  }

  /**
   * Sign up.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicControllerSignUp$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicControllerSignUp(params: PublicControllerSignUp$Params, context?: HttpContext): Observable<void> {
    return this.publicControllerSignUp$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `publicControllerDonate()` */
  static readonly PublicControllerDonatePath = '/api/public/donate';

  /**
   * Submit donation form.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicControllerDonate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicControllerDonate$Response(params: PublicControllerDonate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return publicControllerDonate(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit donation form.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicControllerDonate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicControllerDonate(params: PublicControllerDonate$Params, context?: HttpContext): Observable<void> {
    return this.publicControllerDonate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
