/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approveReport } from '../fn/reporting-controller/approve-report';
import { ApproveReport$Params } from '../fn/reporting-controller/approve-report';
import { generateReport } from '../fn/reporting-controller/generate-report';
import { GenerateReport$Params } from '../fn/reporting-controller/generate-report';
import { getRegisteredReports } from '../fn/reporting-controller/get-registered-reports';
import { GetRegisteredReports$Params } from '../fn/reporting-controller/get-registered-reports';
import { listReports } from '../fn/reporting-controller/list-reports';
import { ListReports$Params } from '../fn/reporting-controller/list-reports';
import { regenerateReport } from '../fn/reporting-controller/regenerate-report';
import { RegenerateReport$Params } from '../fn/reporting-controller/regenerate-report';
import { SuccessResponseArrayKeyValueDto } from '../models/success-response-array-key-value-dto';
import { SuccessResponsePagedResultReportDetailDto } from '../models/success-response-paged-result-report-detail-dto';
import { SuccessResponseReportDetailDto } from '../models/success-response-report-detail-dto';
import { SuccessResponseString } from '../models/success-response-string';

@Injectable({ providedIn: 'root' })
export class ReportingControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRegisteredReports()` */
  static readonly GetRegisteredReportsPath = '/api/report/registered-reports';

  /**
   * Get list of reports that can be generated.
   *
   * GET /reporting/registered-reports
   * Returns the list of all registered report providers.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRegisteredReports()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRegisteredReports$Response(params?: GetRegisteredReports$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayKeyValueDto>> {
    return getRegisteredReports(this.http, this.rootUrl, params, context);
  }

  /**
   * Get list of reports that can be generated.
   *
   * GET /reporting/registered-reports
   * Returns the list of all registered report providers.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRegisteredReports$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRegisteredReports(params?: GetRegisteredReports$Params, context?: HttpContext): Observable<SuccessResponseArrayKeyValueDto> {
    return this.getRegisteredReports$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayKeyValueDto>): SuccessResponseArrayKeyValueDto => r.body)
    );
  }

  /** Path part for operation `generateReport()` */
  static readonly GenerateReportPath = '/api/report/generate/{reportCode}';

  /**
   * generate a report.
   *
   * POST /reporting/trigger/:reportCode
   * Triggers a report generation for the given report code.
   * Uploads the result to DMS and sends email notifications.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateReport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateReport$Response(params: GenerateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseReportDetailDto>> {
    return generateReport(this.http, this.rootUrl, params, context);
  }

  /**
   * generate a report.
   *
   * POST /reporting/trigger/:reportCode
   * Triggers a report generation for the given report code.
   * Uploads the result to DMS and sends email notifications.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateReport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateReport(params: GenerateReport$Params, context?: HttpContext): Observable<SuccessResponseReportDetailDto> {
    return this.generateReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseReportDetailDto>): SuccessResponseReportDetailDto => r.body)
    );
  }

  /** Path part for operation `listReports()` */
  static readonly ListReportsPath = '/api/report/list/{reportCode}';

  /**
   * List report executions for a specific report.
   *
   * GET /report/list/:reportCode
   * Returns a paginated list of report executions for the given report code.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listReports()` instead.
   *
   * This method doesn't expect any request body.
   */
  listReports$Response(params: ListReports$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultReportDetailDto>> {
    return listReports(this.http, this.rootUrl, params, context);
  }

  /**
   * List report executions for a specific report.
   *
   * GET /report/list/:reportCode
   * Returns a paginated list of report executions for the given report code.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listReports$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listReports(params: ListReports$Params, context?: HttpContext): Observable<SuccessResponsePagedResultReportDetailDto> {
    return this.listReports$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultReportDetailDto>): SuccessResponsePagedResultReportDetailDto => r.body)
    );
  }

  /** Path part for operation `approveReport()` */
  static readonly ApproveReportPath = '/api/report/{reportId}/approve';

  /**
   * Approve a report.
   *
   * POST /report/:reportId/approve
   * Approves a specific report.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReport$Response(params: ApproveReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseReportDetailDto>> {
    return approveReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Approve a report.
   *
   * POST /report/:reportId/approve
   * Approves a specific report.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReport(params: ApproveReport$Params, context?: HttpContext): Observable<SuccessResponseReportDetailDto> {
    return this.approveReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseReportDetailDto>): SuccessResponseReportDetailDto => r.body)
    );
  }

  /** Path part for operation `regenerateReport()` */
  static readonly RegenerateReportPath = '/api/report/{reportId}/regenerate';

  /**
   * Regenerate a report.
   *
   * POST /report/:reportId/regenerate
   * Regenerates a specific report.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `regenerateReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  regenerateReport$Response(params: RegenerateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
    return regenerateReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Regenerate a report.
   *
   * POST /report/:reportId/regenerate
   * Regenerates a specific report.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `regenerateReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  regenerateReport(params: RegenerateReport$Params, context?: HttpContext): Observable<SuccessResponseString> {
    return this.regenerateReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseString>): SuccessResponseString => r.body)
    );
  }

}
