/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignRole } from '../fn/user-controller/assign-role';
import { AssignRole$Params } from '../fn/user-controller/assign-role';
import { assignRoleToUser } from '../fn/user-controller/assign-role-to-user';
import { AssignRoleToUser$Params } from '../fn/user-controller/assign-role-to-user';
import { create } from '../fn/user-controller/create';
import { Create$Params } from '../fn/user-controller/create';
import { getLoggedInUser } from '../fn/user-controller/get-logged-in-user';
import { GetLoggedInUser$Params } from '../fn/user-controller/get-logged-in-user';
import { getUser } from '../fn/user-controller/get-user';
import { GetUser$Params } from '../fn/user-controller/get-user';
import { listUsers } from '../fn/user-controller/list-users';
import { ListUsers$Params } from '../fn/user-controller/list-users';
import { referenceData } from '../fn/user-controller/reference-data';
import { ReferenceData$Params } from '../fn/user-controller/reference-data';
import { SuccessResponsePagedResultUserDto } from '../models/success-response-paged-result-user-dto';
import { SuccessResponseUserDto } from '../models/success-response-user-dto';
import { SuccessResponseUserRefDataDto } from '../models/success-response-user-ref-data-dto';
import { SuccessResponseVoid } from '../models/success-response-void';
import { updateMyDetails } from '../fn/user-controller/update-my-details';
import { UpdateMyDetails$Params } from '../fn/user-controller/update-my-details';
import { updateUser } from '../fn/user-controller/update-user';
import { UpdateUser$Params } from '../fn/user-controller/update-user';

@Injectable({ providedIn: 'root' })
export class UserControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listUsers()` */
  static readonly ListUsersPath = '/api/users';

  /**
   * Get list of users with pagination and filters.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUsers$Response(params?: ListUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultUserDto>> {
    return listUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * Get list of users with pagination and filters.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUsers(params?: ListUsers$Params, context?: HttpContext): Observable<SuccessResponsePagedResultUserDto> {
    return this.listUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultUserDto>): SuccessResponsePagedResultUserDto => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/api/users';

  /**
   * Create a new user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserDto>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<SuccessResponseUserDto> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseUserDto>): SuccessResponseUserDto => r.body)
    );
  }

  /** Path part for operation `getUser()` */
  static readonly GetUserPath = '/api/users/{id}';

  /**
   * Get user by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUser$Response(params: GetUser$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserDto>> {
    return getUser(this.http, this.rootUrl, params, context);
  }

  /**
   * Get user by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUser(params: GetUser$Params, context?: HttpContext): Observable<SuccessResponseUserDto> {
    return this.getUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseUserDto>): SuccessResponseUserDto => r.body)
    );
  }

  /** Path part for operation `updateUser()` */
  static readonly UpdateUserPath = '/api/users/{id}';

  /**
   * Update user (admin update).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser$Response(params: UpdateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserDto>> {
    return updateUser(this.http, this.rootUrl, params, context);
  }

  /**
   * Update user (admin update).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser(params: UpdateUser$Params, context?: HttpContext): Observable<SuccessResponseUserDto> {
    return this.updateUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseUserDto>): SuccessResponseUserDto => r.body)
    );
  }

  /** Path part for operation `getLoggedInUser()` */
  static readonly GetLoggedInUserPath = '/api/users/profile/me';

  /**
   * Get logged in user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLoggedInUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLoggedInUser$Response(params?: GetLoggedInUser$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserDto>> {
    return getLoggedInUser(this.http, this.rootUrl, params, context);
  }

  /**
   * Get logged in user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLoggedInUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLoggedInUser(params?: GetLoggedInUser$Params, context?: HttpContext): Observable<SuccessResponseUserDto> {
    return this.getLoggedInUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseUserDto>): SuccessResponseUserDto => r.body)
    );
  }

  /** Path part for operation `updateMyDetails()` */
  static readonly UpdateMyDetailsPath = '/api/users/profile/me';

  /**
   * Update user profile (self-update).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMyDetails()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyDetails$Response(params: UpdateMyDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserDto>> {
    return updateMyDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Update user profile (self-update).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMyDetails$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyDetails(params: UpdateMyDetails$Params, context?: HttpContext): Observable<SuccessResponseUserDto> {
    return this.updateMyDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseUserDto>): SuccessResponseUserDto => r.body)
    );
  }

  /** Path part for operation `referenceData()` */
  static readonly ReferenceDataPath = '/api/users/referenceData';

  /**
   * Get logged in user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `referenceData()` instead.
   *
   * This method doesn't expect any request body.
   */
  referenceData$Response(params?: ReferenceData$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserRefDataDto>> {
    return referenceData(this.http, this.rootUrl, params, context);
  }

  /**
   * Get logged in user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `referenceData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  referenceData(params?: ReferenceData$Params, context?: HttpContext): Observable<SuccessResponseUserRefDataDto> {
    return this.referenceData$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseUserRefDataDto>): SuccessResponseUserRefDataDto => r.body)
    );
  }

  /** Path part for operation `assignRole()` */
  static readonly AssignRolePath = '/api/users/{id}/assign-role';

  /**
   * Assign Role to user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignRole$Response(params: AssignRole$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseVoid>> {
    return assignRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Assign Role to user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignRole(params: AssignRole$Params, context?: HttpContext): Observable<SuccessResponseVoid> {
    return this.assignRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseVoid>): SuccessResponseVoid => r.body)
    );
  }

  /** Path part for operation `assignRoleToUser()` */
  static readonly AssignRoleToUserPath = '/api/users/role/{roleCode}/assign';

  /**
   * Assign Role to user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignRoleToUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignRoleToUser$Response(params: AssignRoleToUser$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseVoid>> {
    return assignRoleToUser(this.http, this.rootUrl, params, context);
  }

  /**
   * Assign Role to user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignRoleToUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignRoleToUser(params: AssignRoleToUser$Params, context?: HttpContext): Observable<SuccessResponseVoid> {
    return this.assignRoleToUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseVoid>): SuccessResponseVoid => r.body)
    );
  }

}
