/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { additionalFields } from '../fn/workflow-controller/additional-fields';
import { AdditionalFields$Params } from '../fn/workflow-controller/additional-fields';
import { getInstance } from '../fn/workflow-controller/get-instance';
import { GetInstance$Params } from '../fn/workflow-controller/get-instance';
import { listInstancesByMe } from '../fn/workflow-controller/list-instances-by-me';
import { ListInstancesByMe$Params } from '../fn/workflow-controller/list-instances-by-me';
import { listInstancesForMe } from '../fn/workflow-controller/list-instances-for-me';
import { ListInstancesForMe$Params } from '../fn/workflow-controller/list-instances-for-me';
import { listTasks } from '../fn/workflow-controller/list-tasks';
import { ListTasks$Params } from '../fn/workflow-controller/list-tasks';
import { startWorkflow } from '../fn/workflow-controller/start-workflow';
import { StartWorkflow$Params } from '../fn/workflow-controller/start-workflow';
import { SuccessResponseArrayFieldAttributeDto } from '../models/success-response-array-field-attribute-dto';
import { SuccessResponsePagedResultWorkflowInstanceDto } from '../models/success-response-paged-result-workflow-instance-dto';
import { SuccessResponsePagedResultWorkflowTaskDto } from '../models/success-response-paged-result-workflow-task-dto';
import { SuccessResponseWorkflowInstanceDto } from '../models/success-response-workflow-instance-dto';
import { SuccessResponseWorkflowRefDataDto } from '../models/success-response-workflow-ref-data-dto';
import { SuccessResponseWorkflowTaskDto } from '../models/success-response-workflow-task-dto';
import { updateTask } from '../fn/workflow-controller/update-task';
import { UpdateTask$Params } from '../fn/workflow-controller/update-task';
import { workflowReferenceData } from '../fn/workflow-controller/workflow-reference-data';
import { WorkflowReferenceData$Params } from '../fn/workflow-controller/workflow-reference-data';

@Injectable({ providedIn: 'root' })
export class WorkflowControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `startWorkflow()` */
  static readonly StartWorkflowPath = '/api/workflows/create';

  /**
   * Start a new workflow instance.
   *
   * **Required Permissions:**
   * - `create:request`
   * _(All permissions required)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `startWorkflow()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  startWorkflow$Response(params: StartWorkflow$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowInstanceDto>> {
    return startWorkflow(this.http, this.rootUrl, params, context);
  }

  /**
   * Start a new workflow instance.
   *
   * **Required Permissions:**
   * - `create:request`
   * _(All permissions required)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `startWorkflow$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  startWorkflow(params: StartWorkflow$Params, context?: HttpContext): Observable<SuccessResponseWorkflowInstanceDto> {
    return this.startWorkflow$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseWorkflowInstanceDto>): SuccessResponseWorkflowInstanceDto => r.body)
    );
  }

  /** Path part for operation `updateTask()` */
  static readonly UpdateTaskPath = '/api/workflows/{id}/tasks/{taskId}/update';

  /**
   * Update a workflow task.
   *
   * **Required Permissions:**
   * - `update:work`
   * _(All permissions required)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTask()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTask$Response(params: UpdateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowTaskDto>> {
    return updateTask(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a workflow task.
   *
   * **Required Permissions:**
   * - `update:work`
   * _(All permissions required)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTask$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTask(params: UpdateTask$Params, context?: HttpContext): Observable<SuccessResponseWorkflowTaskDto> {
    return this.updateTask$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseWorkflowTaskDto>): SuccessResponseWorkflowTaskDto => r.body)
    );
  }

  /** Path part for operation `getInstance()` */
  static readonly GetInstancePath = '/api/workflows/{id}/instance';

  /**
   * Get workflow instance by ID.
   *
   * **Required Permissions:**
   * - `read:request`
   * _(All permissions required)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInstance()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInstance$Response(params: GetInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowInstanceDto>> {
    return getInstance(this.http, this.rootUrl, params, context);
  }

  /**
   * Get workflow instance by ID.
   *
   * **Required Permissions:**
   * - `read:request`
   * _(All permissions required)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInstance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInstance(params: GetInstance$Params, context?: HttpContext): Observable<SuccessResponseWorkflowInstanceDto> {
    return this.getInstance$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseWorkflowInstanceDto>): SuccessResponseWorkflowInstanceDto => r.body)
    );
  }

  /** Path part for operation `listInstancesForMe()` */
  static readonly ListInstancesForMePath = '/api/workflows/instances/forMe';

  /**
   * List workflow instances.
   *
   * **Required Permissions:**
   * - `read:request`
   * _(All permissions required)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listInstancesForMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  listInstancesForMe$Response(params?: ListInstancesForMe$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>> {
    return listInstancesForMe(this.http, this.rootUrl, params, context);
  }

  /**
   * List workflow instances.
   *
   * **Required Permissions:**
   * - `read:request`
   * _(All permissions required)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listInstancesForMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listInstancesForMe(params?: ListInstancesForMe$Params, context?: HttpContext): Observable<SuccessResponsePagedResultWorkflowInstanceDto> {
    return this.listInstancesForMe$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>): SuccessResponsePagedResultWorkflowInstanceDto => r.body)
    );
  }

  /** Path part for operation `listInstancesByMe()` */
  static readonly ListInstancesByMePath = '/api/workflows/instances/byMe';

  /**
   * List workflow instances.
   *
   * **Required Permissions:**
   * - `read:request`
   * _(All permissions required)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listInstancesByMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  listInstancesByMe$Response(params?: ListInstancesByMe$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>> {
    return listInstancesByMe(this.http, this.rootUrl, params, context);
  }

  /**
   * List workflow instances.
   *
   * **Required Permissions:**
   * - `read:request`
   * _(All permissions required)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listInstancesByMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listInstancesByMe(params?: ListInstancesByMe$Params, context?: HttpContext): Observable<SuccessResponsePagedResultWorkflowInstanceDto> {
    return this.listInstancesByMe$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>): SuccessResponsePagedResultWorkflowInstanceDto => r.body)
    );
  }

  /** Path part for operation `listTasks()` */
  static readonly ListTasksPath = '/api/workflows/tasks/forMe';

  /**
   * List workflow tasks.
   *
   * **Required Permissions:**
   * - `read:work`
   * _(All permissions required)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listTasks()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTasks$Response(params?: ListTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultWorkflowTaskDto>> {
    return listTasks(this.http, this.rootUrl, params, context);
  }

  /**
   * List workflow tasks.
   *
   * **Required Permissions:**
   * - `read:work`
   * _(All permissions required)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listTasks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTasks(params?: ListTasks$Params, context?: HttpContext): Observable<SuccessResponsePagedResultWorkflowTaskDto> {
    return this.listTasks$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultWorkflowTaskDto>): SuccessResponsePagedResultWorkflowTaskDto => r.body)
    );
  }

  /** Path part for operation `workflowReferenceData()` */
  static readonly WorkflowReferenceDataPath = '/api/workflows/static/referenceData';

  /**
   * Get static reference data.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowReferenceData()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowReferenceData$Response(params?: WorkflowReferenceData$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowRefDataDto>> {
    return workflowReferenceData(this.http, this.rootUrl, params, context);
  }

  /**
   * Get static reference data.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowReferenceData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowReferenceData(params?: WorkflowReferenceData$Params, context?: HttpContext): Observable<SuccessResponseWorkflowRefDataDto> {
    return this.workflowReferenceData$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseWorkflowRefDataDto>): SuccessResponseWorkflowRefDataDto => r.body)
    );
  }

  /** Path part for operation `additionalFields()` */
  static readonly AdditionalFieldsPath = '/api/workflows/static/additionalFields';

  /**
   * Get additional fields for a workflow type.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `additionalFields()` instead.
   *
   * This method doesn't expect any request body.
   */
  additionalFields$Response(params: AdditionalFields$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayFieldAttributeDto>> {
    return additionalFields(this.http, this.rootUrl, params, context);
  }

  /**
   * Get additional fields for a workflow type.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `additionalFields$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  additionalFields(params: AdditionalFields$Params, context?: HttpContext): Observable<SuccessResponseArrayFieldAttributeDto> {
    return this.additionalFields$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayFieldAttributeDto>): SuccessResponseArrayFieldAttributeDto => r.body)
    );
  }

}
