/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UserControllerService } from './services/user-controller.service';
import { EventControllerService } from './services/event-controller.service';
import { RequestControllerService } from './services/request-controller.service';
import { NoticeControllerService } from './services/notice-controller.service';
import { DonationControllerService } from './services/donation-controller.service';
import { CommonControllerService } from './services/common-controller.service';
import { AdminControllerService } from './services/admin-controller.service';
import { AccountControllerService } from './services/account-controller.service';
import { TestControllerService } from './services/test-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UserControllerService,
    EventControllerService,
    RequestControllerService,
    NoticeControllerService,
    DonationControllerService,
    CommonControllerService,
    AdminControllerService,
    AccountControllerService,
    TestControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
