/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseListHistoryDetail } from '../../models/success-response-list-history-detail';

export interface GetHistories$Params {
  id: string;
  'Correlation-Id'?: string;
}

export function getHistories(http: HttpClient, rootUrl: string, params: GetHistories$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseListHistoryDetail>> {
  const rb = new RequestBuilder(rootUrl, getHistories.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('Correlation-Id', params['Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseListHistoryDetail>;
    })
  );
}

getHistories.PATH = '/api/donation/{id}/changes';
