/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DonationDetailFilter } from '../../models/donation-detail-filter';
import { SuccessResponsePaginateDonationDetail } from '../../models/success-response-paginate-donation-detail';

export interface GetGuestDonations$Params {
  pageIndex?: number;
  pageSize?: number;
  filter: DonationDetailFilter;
  'Correlation-Id'?: string;
}

export function getGuestDonations(http: HttpClient, rootUrl: string, params: GetGuestDonations$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePaginateDonationDetail>> {
  const rb = new RequestBuilder(rootUrl, getGuestDonations.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('filter', params.filter, {});
    rb.header('Correlation-Id', params['Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePaginateDonationDetail>;
    })
  );
}

getGuestDonations.PATH = '/api/donation/list/guest';
