/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultSchedulerLogDto } from '../../models/success-response-paged-result-scheduler-log-dto';

export interface GetTriggerLogs$Params {
  pageIndex?: number;
  pageSize?: number;
}

export function getTriggerLogs(http: HttpClient, rootUrl: string, params?: GetTriggerLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultSchedulerLogDto>> {
  const rb = new RequestBuilder(rootUrl, getTriggerLogs.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultSchedulerLogDto>;
    })
  );
}

getTriggerLogs.PATH = '/api/cron/trigger-logs';
