/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseArrayCronJobDto } from '../../models/success-response-array-cron-job-dto';

export interface GetScheduledJobs$Params {
}

export function getScheduledJobs(http: HttpClient, rootUrl: string, params?: GetScheduledJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayCronJobDto>> {
  const rb = new RequestBuilder(rootUrl, getScheduledJobs.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseArrayCronJobDto>;
    })
  );
}

getScheduledJobs.PATH = '/api/cron/jobs';
