/** True when the value is an absolute http(s) image URL. */
export function isAbsoluteImageUrl(src: string): boolean {
  return /^https?:\/\//i.test(src.trim())
}

/**
 * Normalize an image source from content or API data.
 * Supports internal paths (`/img/photo.jpg`) and external URLs (`https://...`).
 */
export function resolveImageSrc(src: string): string {
  const trimmed = src.trim()
  if (!trimmed) return trimmed
  if (isAbsoluteImageUrl(trimmed)) return trimmed
  if (trimmed.startsWith('//')) return `https:${trimmed}`
  if (trimmed.startsWith('/')) return trimmed
  return `/${trimmed}`
}

/** Build an absolute URL for Open Graph, JSON-LD, and metadata. */
export function toAbsoluteImageUrl(src: string, baseUrl: string): string {
  const resolved = resolveImageSrc(src)
  if (isAbsoluteImageUrl(resolved)) return resolved
  const base = baseUrl.replace(/\/$/, '')
  return `${base}${resolved.startsWith('/') ? '' : '/'}${resolved}`
}

/** WebP sibling path for internal raster images (generated by scripts/generate-assets.mjs). */
export function toWebpSrc(src: string): string | null {
  const resolved = resolveImageSrc(src)
  if (isAbsoluteImageUrl(resolved)) return null
  if (/\.(svg|webp|gif|ico)$/i.test(resolved)) return null
  if (!/\.(jpe?g|png)$/i.test(resolved)) return null
  return resolved.replace(/\.(jpe?g|png)$/i, '.webp')
}

export const IMAGE_FIELD_KEYS = new Set([
  'image',
  'picture',
  'logo',
  'qrImage',
  'coverImage',
])


