/**
 * Generates src/environments/env.generated.ts from the process environment.
 *
 * The public site gets this for free: Next inlines process.env.NEXT_PUBLIC_*
 * at build time and src/lib/config/env.ts reads it. Angular's builder has no
 * equivalent, so the values are written into a generated module instead and
 * src/environments/environment.ts plays the part of env.ts.
 *
 * This script knows nothing beyond the prefix. It iterates process.env, keeps
 * the NG_APP_* entries and writes them out; it holds no list of expected keys
 * and no per-key rules. Adding a variable needs no change here, just a line in
 * .env and a read in environment.ts.
 *
 * Loading .env is the caller's job, not this script's: the npm scripts pass
 * Node's --env-file-if-exists=.env, which merges the file into process.env
 * before this runs. Deploy pipelines supply the values as real environment
 * variables and ship no .env, so the flag finds nothing and the same code path
 * serves both. Real environment variables always win, because Node does not let
 * a file overwrite a variable that is already set.
 *
 * The NG_APP_ prefix is a safety filter rather than a naming convention.
 * process.env holds the entire machine environment, and everything emitted here
 * is inlined into a browser bundle that anyone can read, so only deliberately
 * prefixed, non-secret values qualify.
 *
 * Every key becomes one top-level `export const`, which environment.ts imports
 * by name. That is also the only form Angular's compiler will evaluate when it
 * resolves NgModule metadata, so a flag read this way can decide which modules
 * the graph includes.
 *
 * Values become the literal they look like, so booleans and integers arrive as
 * real booleans and numbers rather than strings needing coercion. A key that was
 * never supplied is a compile error naming it, so the environment is the only
 * place defaults live; there are none in TypeScript.
 *
 * Usage: node --env-file-if-exists=.env scripts/generate-env.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_FILE = join(APP_ROOT, 'src', 'environments', 'env.generated.ts');

const PREFIX = 'NG_APP_';

/* Sorted so the generated file is stable between runs and easy to diff. Blank
   values are kept rather than dropped: a declared-but-empty variable has to stay
   in the output, otherwise reading it in environment.ts would fail to compile
   and a deliberately blank value, such as the Auth0 keys during local work,
   could not be expressed. */
const values = Object.entries(process.env)
  .filter(([key, value]) => key.startsWith(PREFIX) && value != null)
  .sort(([a], [b]) => a.localeCompare(b));

/**
 * Emits the value as the TypeScript literal it looks like, so environment.ts
 * gets a real boolean or number instead of a string it has to convert. Only
 * exact `true`/`false` and plain integers are narrowed; anything else stays a
 * string, which keeps values like the OneSignal UUID and dotted versions intact.
 */
function literal(value) {
  const lowered = value.toLowerCase();
  if (lowered === 'true' || lowered === 'false') return lowered;
  if (/^-?\d+$/.test(value)) return value;
  return JSON.stringify(value);
}

/* An environment variable may legally contain characters a TypeScript identifier
   cannot, and there is no valid `export const` name to give such a key. Nothing
   in the app uses one today, so it is skipped with a warning rather than
   emitting a file that will not parse. */
const isIdentifier = (key) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
const [named, skipped] = [
  values.filter(([key]) => isIdentifier(key)),
  values.filter(([key]) => !isIdentifier(key)),
];

const constants = named
  .map(([key, value]) => `export const ${key} = ${literal(value)};`)
  .join('\n');

const contents = `// Generated by scripts/generate-env.mjs from the NG_APP_* environment variables.
// This file is gitignored and rewritten from scratch on every build, so change
// values in .env or in the pipeline's variables instead (see .env.example).
//

${constants}
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, contents, 'utf8');

console.log(
  `[generate-env] ${named.length} ${PREFIX}* variables -> src/environments/env.generated.ts`
);

if (skipped.length > 0) {
  console.warn(
    `[generate-env] Skipped, not usable as a TypeScript name: ${skipped
      .map(([key]) => key)
      .join(', ')}`
  );
}

/* Without this the failure surfaces as a wall of "has no exported member" errors
   from environment.ts, which points at the symptom, not the cause. */
if (named.length === 0) {
  console.warn(
    `[generate-env] No ${PREFIX}* variables found, so the build will not compile.\n` +
      '               Locally: copy apps/internal-app/.env.example to .env.\n' +
      '               In CI: supply the keys as environment variables.'
  );
}
