/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseImportantLinks } from '../../models/success-response-important-links';

export interface GetUsefulLinks$Params {
  'Correlation-Id'?: string;
}

export function getUsefulLinks(http: HttpClient, rootUrl: string, params?: GetUsefulLinks$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseImportantLinks>> {
  const rb = new RequestBuilder(rootUrl, getUsefulLinks.PATH, 'get');
  if (params) {
    rb.header('Correlation-Id', params['Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseImportantLinks>;
    })
  );
}

getUsefulLinks.PATH = '/api/common/useful-links';
