/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdditionalField {
  id?: string;
  key?: 'firstName' | 'lastName' | 'email' | 'dialCode' | 'mobileNumber' | 'hometown' | 'reasonForJoining' | 'howDoUKnowAboutNabarun' | 'password' | 'name' | 'amount' | 'paymentMethod' | 'paidToAccount' | 'decision' | 'remarks' | 'confirmation';
  mandatory?: boolean;
  name?: string;
  options?: Array<string>;
  type?: string;
  updateField?: boolean;
  value?: string;
  valueType?: string;
}
