/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CronServiceDetail {
  parameters?: {
[key: string]: string;
};
  triggerName?: 'DONATION_REMINDER_EMAIL' | 'TASK_REMINDER_EMAIL' | 'CREATE_DONATION' | 'UPDATE_DONATION' | 'SYNC_USERS';
}
