/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentMapping } from '../models/document-mapping';
export interface DocumentDetailUpload {
  base64Content?: string;
  contentType?: string;
  documentMapping?: Array<DocumentMapping>;
  originalFileName?: string;
}
