/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentDetail {
  docId?: string;
  documentIndexId?: string;
  downloadURL?: string;
  generatedDoc?: boolean;
  image?: boolean;
  originalFileName?: string;
}
