/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DonationStatus {
  Raised = 'RAISED',
  Paid = 'PAID',
  Pending = 'PENDING',
  PaymentFailed = 'PAYMENT_FAILED',
  PayLater = 'PAY_LATER',
  Cancelled = 'CANCELLED',
  UpdateMistake = 'UPDATE_MISTAKE'
}
