/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventDetailFilter {
  completed?: boolean;
  eventTitle?: string;
  fromDate?: string;
  id?: string;
  toDate?: string;
}
