/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDetail } from '../models/account-detail';
import { ExpenseItemDetail } from '../models/expense-item-detail';
import { UserDetail } from '../models/user-detail';
export interface ExpenseDetail {
  createdBy?: UserDetail;
  createdOn?: string;
  description?: string;
  expenseDate?: string;
  expenseItems?: Array<ExpenseItemDetail>;
  expenseRefId?: string;
  expenseRefType?: 'EVENT' | 'OTHER';
  finalAmount?: number;
  finalizedBy?: UserDetail;
  finalizedOn?: string;
  id?: string;
  isAdmin?: boolean;
  isDeligated?: boolean;
  name?: string;
  paidBy?: UserDetail;
  rejectedBy?: UserDetail;
  rejectedOn?: string;
  remarks?: string;
  settledBy?: UserDetail;
  settledOn?: string;
  settlementAccount?: AccountDetail;
  status?: 'DRAFT' | 'SUBMITTED' | 'FINALIZED' | 'SETTLED' | 'REJECTED';
  txnNumber?: string;
}
