/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpenseDetailFilter {
  endDate?: string;
  expenseId?: string;
  expenseRefId?: string;
  expenseStatus?: Array<'DRAFT' | 'SUBMITTED' | 'FINALIZED' | 'SETTLED' | 'REJECTED'>;
  payerId?: string;
  startDate?: string;
}
