/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LinkCategoryDetail } from '../models/link-category-detail';
export interface ImportantLinks {
  policies?: Array<LinkCategoryDetail>;
  userGuides?: Array<LinkCategoryDetail>;
}
