/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobDetailFilter {
  end?: string;
  id?: string;
  name?: string;
  start?: string;
  status?: Array<'QUEUED' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED'>;
  triggerId?: string;
}
