/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValue } from '../models/key-value';
export interface LinkCategoryDetail {
  documents?: Array<KeyValue>;
  name?: string;
}
