/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankDetail } from '../models/bank-detail';
import { UpiDetail } from '../models/upi-detail';
export interface PayableAccDetail {
  bankDetail?: BankDetail;
  id?: string;
  upiDetail?: UpiDetail;
}
