/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdditionalField } from '../models/additional-field';
import { RequestType } from '../models/request-type';
import { UserDetail } from '../models/user-detail';
export interface RequestDetail {
  additionalFields?: Array<AdditionalField>;
  createdOn?: string;
  delegated?: boolean;
  delegatedRequester?: UserDetail;
  description?: string;
  id?: string;
  name?: string;
  remarks?: string;
  requester?: UserDetail;
  resolvedOn?: string;
  status?: 'AWAITING_L1_APPROVAL' | 'AWAITING_L2_APPROVAL' | 'AWAITING_L2_APPROVAL_MM' | 'APPROVED_ONBOARDING' | 'APPROVED_EXIT' | 'REJECTED' | 'CANCELLED' | 'PAYMENT_COLLECTION_PENDING' | 'PAYMENT_CONFIRMATION_PENDING' | 'PAYMENT_COLLECTED' | 'NO_PAYMENT' | 'AWAITING_APPROVAL_MM' | 'APPROVED_DONATION_PAUSE' | 'COMPLETED' | 'AWAITING_USER_RESPONSE';
  type?: RequestType;
}
