/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuccessResponseMapStringObject {
  info?: string;
  messages?: Array<string>;
  responsePayload?: {
[key: string]: {
};
};
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
