/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginateJobDetail } from '../models/paginate-job-detail';
export interface SuccessResponsePaginateJobDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: PaginateJobDetail;
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
