/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentDetail } from '../models/document-detail';
export interface SuccessResponseListDocumentDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: Array<DocumentDetail>;
  status?: number;
  timestamp?: string;
}
