/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginateAccountDetail } from '../models/paginate-account-detail';
export interface SuccessResponsePaginateAccountDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: PaginateAccountDetail;
  status?: number;
  timestamp?: string;
}
