/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NoticeDetail } from '../models/notice-detail';
export interface SuccessResponseNoticeDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: NoticeDetail;
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
