/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginateNoticeDetail } from '../models/paginate-notice-detail';
export interface SuccessResponsePaginateNoticeDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: PaginateNoticeDetail;
  status?: number;
  timestamp?: string;
}
