/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseItemDetail } from '../models/expense-item-detail';
export interface SuccessResponseExpenseItemDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: ExpenseItemDetail;
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
