/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDetail } from '../models/account-detail';
export interface SuccessResponseAccountDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: AccountDetail;
  status?: number;
  timestamp?: string;
}
