/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportantLinks } from '../models/important-links';
export interface SuccessResponseImportantLinks {
  info?: string;
  messages?: Array<string>;
  responsePayload?: ImportantLinks;
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
