/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDetail } from '../models/user-detail';
export interface SuccessResponseUserDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: UserDetail;
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
