/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuccessResponseString {
  info?: string;
  messages?: Array<string>;
  responsePayload?: string;
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
