/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValue } from '../models/key-value';
export interface SuccessResponseMapStringListKeyValue {
  info?: string;
  messages?: Array<string>;
  responsePayload?: {
[key: string]: Array<KeyValue>;
};
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
