/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiKeyDetail } from '../models/api-key-detail';
export interface SuccessResponseListApiKeyDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: Array<ApiKeyDetail>;
  status?: number;
  timestamp?: string;
  traceId?: string;
  version?: string;
}
