/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkDetail } from '../models/work-detail';
export interface SuccessResponseWorkDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: WorkDetail;
  status?: number;
  timestamp?: string;
}
