/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginateDonationDetail } from '../models/paginate-donation-detail';
export interface SuccessResponsePaginateDonationDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: PaginateDonationDetail;
  status?: number;
  timestamp?: string;
}
