/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginateWorkDetail } from '../models/paginate-work-detail';
export interface SuccessResponsePaginateWorkDetail {
  info?: string;
  messages?: Array<string>;
  responsePayload?: PaginateWorkDetail;
  status?: number;
  timestamp?: string;
}
