/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionDetailFilter {
  endDate?: string;
  startDate?: string;
  txnId?: string;
  txnRefId?: string;
  txnRefType?: 'DONATION' | 'NONE' | 'EXPENSE';
  txnStatus?: Array<'SUCCESS' | 'FAILURE' | 'REVERT'>;
  txnType?: Array<'IN' | 'OUT' | 'TRANSFER'>;
}
