/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDetail } from '../models/account-detail';
export interface TransactionDetail {
  accBalance?: number;
  comment?: string;
  transferFrom?: AccountDetail;
  transferTo?: AccountDetail;
  txnAmount?: number;
  txnDate?: string;
  txnDescription?: string;
  txnId?: string;
  txnParticulars?: string;
  txnRefId?: string;
  txnRefType?: 'DONATION' | 'NONE' | 'EXPENSE';
  txnStatus?: 'SUCCESS' | 'FAILURE' | 'REVERT';
  txnType?: 'IN' | 'OUT' | 'TRANSFER';
}
