/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpiDetail {
  mobileNumber?: string;
  payeeName?: string;
  qrData?: string;
  upiId?: string;
}
