/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkDetailFilter {
  completed?: boolean;
  fromDate?: string;
  requestId?: string;
  toDate?: string;
  workId?: string;
}
