/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdditionalField } from '../models/additional-field';
import { UserDetail } from '../models/user-detail';
export interface WorkDetail {
  additionalFields?: Array<AdditionalField>;
  createdOn?: string;
  decisionDate?: string;
  decisionOwner?: UserDetail;
  description?: string;
  id?: string;
  pendingWith?: Array<UserDetail>;
  pendingWithRoles?: Array<'MEMBER' | 'CASHIER' | 'ASSISTANT_CASHIER' | 'TREASURER' | 'GROUP_COORDINATOR' | 'ASST_GROUP_COORDINATOR' | 'SECRETARY' | 'ASST_SECRETARY' | 'COMMUNITY_MANAGER' | 'ASST_COMMUNITY_MANAGER' | 'PRESIDENT' | 'VICE_PRESIDENT' | 'TECHNICAL_SPECIALIST'>;
  stepCompleted?: boolean;
  workType?: 'DECISION' | 'NA' | 'CONFIRMATION' | 'USER_INPUT';
  workflowId?: string;
  workflowStatus?: 'AWAITING_L1_APPROVAL' | 'AWAITING_L2_APPROVAL' | 'AWAITING_L2_APPROVAL_MM' | 'APPROVED_ONBOARDING' | 'APPROVED_EXIT' | 'REJECTED' | 'CANCELLED' | 'PAYMENT_COLLECTION_PENDING' | 'PAYMENT_CONFIRMATION_PENDING' | 'PAYMENT_COLLECTED' | 'NO_PAYMENT' | 'AWAITING_APPROVAL_MM' | 'APPROVED_DONATION_PAUSE' | 'COMPLETED' | 'AWAITING_USER_RESPONSE';
}
