/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseExpenseDetailDto } from '../../models/success-response-expense-detail-dto';
import { UpdateExpenseDto } from '../../models/update-expense-dto';

export interface UpdateExpense$Params {
  id: string;
      body: UpdateExpenseDto
}

export function updateExpense(http: HttpClient, rootUrl: string, params: UpdateExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseExpenseDetailDto>> {
  const rb = new RequestBuilder(rootUrl, updateExpense.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseExpenseDetailDto>;
    })
  );
}

updateExpense.PATH = '/api/expense/{id}/update';
