/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseArrayString } from '../../models/success-response-array-string';

export interface GetScopes$Params {

/**
 * OAuth provider (e.g., google)
 */
  provider: string;
}

export function getScopes(http: HttpClient, rootUrl: string, params: GetScopes$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayString>> {
  const rb = new RequestBuilder(rootUrl, getScopes.PATH, 'get');
  if (params) {
    rb.path('provider', params.provider, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseArrayString>;
    })
  );
}

getScopes.PATH = '/api/auth/oauth/{provider}/scopes';
