/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface OAuthControllerGetGmailAuthUrl$Params {
  scopes: string;

/**
 * Optional state parameter for OAuth flow
 */
  state?: string;
}

export function oAuthControllerGetGmailAuthUrl(http: HttpClient, rootUrl: string, params: OAuthControllerGetGmailAuthUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, oAuthControllerGetGmailAuthUrl.PATH, 'get');
  if (params) {
    rb.query('scopes', params.scopes, {});
    rb.query('state', params.state, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

oAuthControllerGetGmailAuthUrl.PATH = '/api/auth/oauth/google/auth-url';
