/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValue } from '../models/key-value';
export interface AccountRefDataDto {
  accountStatuses?: Array<KeyValue>;
  accountTypes?: Array<KeyValue>;
  transactionRefTypes?: Array<KeyValue>;
}
