/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValueDto } from '../models/key-value-dto';
export interface AccountRefDataDto {
  accountStatuses?: Array<KeyValueDto>;
  accountTypes?: Array<KeyValueDto>;
  expenseStatuses?: Array<KeyValueDto>;
  transactionRefTypes?: Array<KeyValueDto>;
}
