/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankDetailDto } from '../models/bank-detail-dto';
import { UpiDetailDto } from '../models/upi-detail-dto';
export interface AccountDetailDto {
  accountHolder?: string;
  accountHolderName?: string;
  accountStatus: 'ACTIVE' | 'CLOSED';
  accountType: 'PRINCIPAL' | 'GENERAL' | 'DONATION' | 'PUBLIC_DONATION' | 'WALLET';
  activatedOn?: string;
  balance?: number;
  bankDetail?: BankDetailDto;
  id: string;
  upiDetail?: UpiDetailDto;
}
