/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityDetailDto {
  actualCost?: number;
  actualEndDate?: string;
  actualParticipants?: number;
  actualStartDate?: string;
  assignedTo?: string;
  createdAt: string;
  currency?: string;
  description?: string;
  endDate?: string;
  estimatedCost?: number;
  expectedParticipants?: number;
  id: string;
  location?: string;
  metadata?: {
};
  name: string;
  organizerId?: string;
  parentActivityId?: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  projectId: string;
  scale: 'TASK' | 'ACTIVITY' | 'EVENT';
  startDate?: string;
  status: 'PLANNED' | 'CONFIRMED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'ON_HOLD' | 'POSTPONED';
  tags: Array<string>;
  type: 'TRAINING' | 'AWARENESS' | 'DISTRIBUTION' | 'SURVEY' | 'MEETING' | 'FIELD_VISIT' | 'DOCUMENTATION' | 'WORKSHOP' | 'SEMINAR' | 'FUNDRAISING' | 'VOLUNTEER_ACTIVITY' | 'CONFERENCE' | 'EXHIBITION' | 'OTHER';
  updatedAt: string;
  venue?: string;
}
