/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssigneeDto } from '../models/assignee-dto';
export interface ActionItemDto {
  assignee?: AssigneeDto;
  completed: boolean;
  description: string;
  recording_playback_url: string;
  recording_timestamp: string;
  user_generated: boolean;
}
