/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CalendarInviteeDto {
  email: string;
  email_domain: string;
  is_external: boolean;
  matched_speaker_display_name?: string;
  name: string;
}
