/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateActivityDto {
  assignedTo?: string;
  currency?: string;
  description?: string;
  endDate?: string;
  estimatedCost?: number;
  expectedParticipants?: number;
  location?: string;
  metadata?: {
};
  name: string;
  organizerId?: string;
  parentActivityId?: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  scale: 'TASK' | 'ACTIVITY' | 'EVENT';
  startDate?: string;
  tags?: Array<string>;
  type: 'TRAINING' | 'AWARENESS' | 'DISTRIBUTION' | 'SURVEY' | 'MEETING' | 'FIELD_VISIT' | 'DOCUMENTATION' | 'WORKSHOP' | 'SEMINAR' | 'FUNDRAISING' | 'VOLUNTEER_ACTIVITY' | 'CONFERENCE' | 'EXHIBITION' | 'OTHER';
  venue?: string;
}
