/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseItemDetailDto } from '../models/expense-item-detail-dto';
export interface CreateExpenseDto {
  currency?: string;
  description: string;
  expenseDate?: string;
  expenseItems?: Array<ExpenseItemDetailDto>;
  expenseRefId?: string;
  expenseRefType: 'OTHER' | 'EVENT' | 'ADHOC' | 'OPERATIONAL' | 'ADMINISTRATIVE';
  name: string;
  payerId: string;
}
