/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MeetingParticipantDto } from '../models/meeting-participant-dto';
export interface CreateMeetingDto {
  agenda?: string;
  attendees: Array<MeetingParticipantDto>;
  description?: string;
  endTime: string;
  location?: string;
  startTime: string;
  summary: string;
  type: 'OFFLINE' | 'ONLINE';
}
