/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CronJobDto {
  description: string;
  enabled: boolean;
  handler: string;
  inputData?: {
};
  name: string;
  nextRun: string;
}
