/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentDto {
  contentType: string;
  fileName: string;
  fileSize: number;
  fileUrl?: string;
  id: string;
  isPublic: boolean;
  uploadedAt: string;
}
