/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DonationSummaryDto {
  hasOutstanding: boolean;
  outstandingAmount: number;
  outstandingMonths: Array<string>;
}
