/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValueDto } from '../models/key-value-dto';
export interface DonationRefDataDto {
  donationStatuses?: Array<KeyValueDto>;
  donationTypes?: Array<KeyValueDto>;
  paymentMethods?: Array<KeyValueDto>;
  upiOptions?: Array<KeyValueDto>;
}
