/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DonationDto {
  amount: number;
  createdAt: string;
  currency: string;
  description?: string;
  donorEmail?: string;
  donorId?: string;
  donorName?: string;
  id: string;
  paidDate?: string;
  raisedDate: string;
  status: string;
  transactionId?: string;
  type: string;
}
