/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDetailDto } from '../models/account-detail-dto';
import { ExpenseItemDetailDto } from '../models/expense-item-detail-dto';
export interface ExpenseDetailDto {
  createdBy?: string;
  createdOn: string;
  description: string;
  expenseDate: string;
  expenseItems?: Array<ExpenseItemDetailDto>;
  expenseRefId?: string;
  expenseRefType?: 'EVENT' | 'OTHER';
  finalAmount: number;
  finalizedBy?: string;
  finalizedOn?: string;
  id: string;
  isAdmin?: boolean;
  isDeligated?: boolean;
  name: string;
  paidBy?: string;
  rejectedBy?: string;
  rejectedOn?: string;
  remarks?: string;
  settledBy?: string;
  settledOn?: string;
  settlementAccount?: AccountDetailDto;
  status: 'DRAFT' | 'SUBMITTED' | 'FINALIZED' | 'SETTLED' | 'REJECTED';
  txnNumber?: string;
}
