/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActionItemDto } from '../models/action-item-dto';
import { CalendarInviteeDto } from '../models/calendar-invitee-dto';
import { CrmMatchesDto } from '../models/crm-matches-dto';
import { DefaultSummaryDto } from '../models/default-summary-dto';
import { RecordedByDto } from '../models/recorded-by-dto';
import { TranscriptDto } from '../models/transcript-dto';
export interface FathomWebhookDto {
  action_items?: Array<ActionItemDto>;
  calendar_invitees?: Array<CalendarInviteeDto>;
  calendar_invitees_domains_type?: string;
  created_at: string;
  crm_matches?: CrmMatchesDto;
  default_summary?: DefaultSummaryDto;
  meeting_title?: string;
  recorded_by?: RecordedByDto;
  recording_end_time: string;
  recording_start_time: string;
  scheduled_end_time: string;
  scheduled_start_time: string;
  share_url: string;
  title: string;
  transcript?: Array<TranscriptDto>;
  url: string;
}
