/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FcmTokenMetadataDto {
  browser?: string;
  createdAt: string;
  deviceName?: string;
  deviceType?: string;
  id: string;
  isActive: boolean;
  lastUsedAt: string;
  os?: string;
  updatedAt: string;
}
