/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FieldAttributeDto {
  fieldOptions: Array<string>;
  fieldType: string;
  isEncrypted: boolean;
  isHidden: boolean;
  isMandatory: boolean;
  key: string;
  type: string;
  value: string;
}
