/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeetingParticipantDto {
  attended?: string;
  email: string;
  id?: string;
  name?: string;
}
