/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValueDto } from '../models/key-value-dto';
export interface ProjectRefDataDto {
  activityPriorities: Array<Array<KeyValueDto>>;
  activityScales: Array<Array<KeyValueDto>>;
  activityStatuses: Array<Array<KeyValueDto>>;
  activityTypes: Array<Array<KeyValueDto>>;
  projectCategories: Array<Array<KeyValueDto>>;
  projectPhases: Array<Array<KeyValueDto>>;
  projectStatuses: Array<Array<KeyValueDto>>;
}
