/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JobMetrics } from '../models/job-metrics';
import { JobPerformanceMetrics } from '../models/job-performance-metrics';
import { QueueHealth } from '../models/queue-health';
export interface QueueStatistics {
  health: QueueHealth;
  metrics: JobMetrics;
  performance: JobPerformanceMetrics;
  timestamp: string;
}
