/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecordedByDto {
  email: string;
  email_domain: string;
  name: string;
  team?: string;
}
