/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportDetailDto {

  /**
   * The timestamp when the report was approved
   */
  approvedAt?: string;

  /**
   * The ID of the user who approved the report
   */
  approvedBy?: string;

  /**
   * The roles that can approve the report
   */
  approvers?: Array<string>;

  /**
   * The timestamp when the report was created
   */
  createdAt: string;

  /**
   * The DMS document ID associated with the report
   */
  dmsDocumentId?: string;

  /**
   * The unique identifier of the report execution
   */
  id: string;

  /**
   * Whether the report requires approval
   */
  needApproval: boolean;

  /**
   * The parameters used to generate the report
   */
  parameters?: {
};

  /**
   * The report code
   */
  reportCode: string;

  /**
   * The ID of the user who requested the report
   */
  requestedById?: string;

  /**
   * The current status of the report
   */
  status: 'DRAFT' | 'APPROVED';

  /**
   * The timestamp when the report was last updated
   */
  updatedAt: string;

  /**
   * The version of the report document
   */
  version: number;

  /**
   * The roles that can view the report
   */
  viewers: Array<string>;

  /**
   * The workflow ID if approval is in progress
   */
  workflowId?: string;
}
