/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QueueDto } from '../models/queue-dto';
export interface SchedulerLogDto {
  executedJobs: Array<QueueDto>;
  skippedJobs: Array<QueueDto>;
  triggerAt: string;
  triggerId?: string;
}
