/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SchedulerLogDto {
  executedJobs: Array<string>;
  skippedJobs: Array<string>;
  triggerAt: string;
  triggerId?: string;
}
