/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDetailDto } from '../models/account-detail-dto';
export interface SettlementSummaryDto {
  amountToReimburse: number;
  createAccount: boolean;
  needsReimbursement: boolean;
  reimbursementAccount?: AccountDetailDto;
  totalExpenseAmount: number;
}
