/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignUpDto {
  contactNumber: string;
  email: string;
  firstName: string;
  hometown: string;
  howDoUKnowAboutUs: string;
  lastName: string;
}
