/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportCategoryDto } from '../models/report-category-dto';
export interface SuccessResponseArrayReportCategoryDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: Array<ReportCategoryDto>;
  timestamp: string;
  traceId: string;
}
