/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DonationRefDataDto } from '../models/donation-ref-data-dto';
export interface SuccessResponseDonationRefDataDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: DonationRefDataDto;
  timestamp: string;
  traceId: string;
}
