/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthTokenDto } from '../models/auth-token-dto';
export interface SuccessResponseArrayAuthTokenDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: Array<AuthTokenDto>;
  timestamp: string;
  traceId: string;
}
