/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserMetricsDto } from '../models/user-metrics-dto';
export interface SuccessResponseUserMetricsDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: UserMetricsDto;
  timestamp: string;
  traceId: string;
}
