/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuccessResponseBoolean {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: boolean;
  timestamp: string;
  traceId: string;
}
