/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MeetingDto } from '../models/meeting-dto';
export interface SuccessResponseMeetingDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: MeetingDto;
  timestamp: string;
  traceId: string;
}
