/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldAttributeDto } from '../models/field-attribute-dto';
export interface SuccessResponseArrayFieldAttributeDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: Array<FieldAttributeDto>;
  timestamp: string;
  traceId: string;
}
