/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityDetailDto } from '../models/activity-detail-dto';
export interface SuccessResponseActivityDetailDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: ActivityDetailDto;
  timestamp: string;
  traceId: string;
}
