/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuccessResponseArrayArray {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: Array<Array<any>>;
  timestamp: string;
  traceId: string;
}
