/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DonationSummaryDto } from '../models/donation-summary-dto';
export interface SuccessResponseDonationSummaryDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: DonationSummaryDto;
  timestamp: string;
  traceId: string;
}
