/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpeakerDto } from '../models/speaker-dto';
export interface TranscriptDto {
  speaker: SpeakerDto;
  text: string;
  timestamp: string;
}
