/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankDetailDto } from '../models/bank-detail-dto';
import { UpiDetailDto } from '../models/upi-detail-dto';
export interface UpdateAccountDto {
  accountStatus?: 'ACTIVE' | 'CLOSED';
  bankDetail?: BankDetailDto;
  description?: string;
  name?: string;
  type?: 'PRINCIPAL' | 'GENERAL' | 'DONATION' | 'PUBLIC_DONATION' | 'WALLET';
  upiDetail?: UpiDetailDto;
}
