/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCommentDto {

  /**
   * The updated content of the comment
   */
  content: string;
}
