/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateReportDto {

  /**
   * The current status of the report
   */
  status: 'DRAFT' | 'APPROVED';
}
