/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTaskDto {

  /**
   * Remarks for task update
   */
  remarks?: string;

  /**
   * Result data from task completion
   */
  resultData?: {
};

  /**
   * Task status
   */
  status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED' | 'SKIPPED';
}
