/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpdateProjectActivityDto } from '../models/update-project-activity-dto';
export interface UpdateProjectDto {
  activities?: Array<UpdateProjectActivityDto>;
  budget?: number;
  category?: 'EDUCATION' | 'HEALTH' | 'ENVIRONMENT' | 'RURAL_DEVELOPMENT' | 'WOMEN_EMPOWERMENT' | 'CHILD_WELFARE' | 'DISASTER_RELIEF' | 'OTHER';
  description?: string;
  endDate?: string;
  location?: string;
  metadata?: {
};
  name?: string;
  phase?: 'INITIATION' | 'PLANNING' | 'EXECUTION' | 'MONITORING' | 'CLOSURE';
  sponsorId?: string;
  status?: 'PLANNING' | 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
  tags?: Array<string>;
  targetBeneficiaryCount?: number;
}
