/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserUpdateAdminDto {
  loginMethods?: Array<'EMAIL' | 'PASSWORD'>;
  roleCodes?: Array<string>;
  status?: 'DRAFT' | 'ACTIVE' | 'BLOCKED' | 'DELETED';
}
