/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValueDto } from '../models/key-value-dto';
export interface UserRefDataDto {
  availableRoles?: Array<KeyValueDto>;
  countries?: Array<KeyValueDto>;
  districts?: Array<KeyValueDto>;
  loginMethods?: Array<KeyValueDto>;
  phoneCodes?: Array<KeyValueDto>;
  states?: Array<KeyValueDto>;
  userGenders?: Array<KeyValueDto>;
  userStatuses?: Array<KeyValueDto>;
  userTitles?: Array<KeyValueDto>;
}
