/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowTaskDto } from '../models/workflow-task-dto';
export interface WorkflowStepDto {
  completedAt?: string;
  createdAt: string;
  description?: string | null;
  id: string;
  name: string;
  orderIndex: number;
  remarks?: string;
  startedAt?: string;
  status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED';
  stepId: string;
  tasks: Array<WorkflowTaskDto>;
  updatedAt: string;
}
