/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeyValueDto } from '../models/key-value-dto';
export interface WorkflowRefDataDto {
  additionalFields?: Array<KeyValueDto>;
  visibleWorkflowTypes?: Array<KeyValueDto>;
  workflowStatuses?: Array<KeyValueDto>;
  workflowTaskStatuses?: Array<KeyValueDto>;
  workflowTypes?: Array<KeyValueDto>;
}
