/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseString } from '../../models/success-response-string';

export interface GetGmailAuthUrl$Params {

/**
 * Space-separated list of OAuth scopes (must be whitelisted)
 */
  scopes?: string;

/**
 * Optional custom state parameter (if not provided, secure state will be generated server-side)
 */
  state?: string;
}

export function getGmailAuthUrl(http: HttpClient, rootUrl: string, params?: GetGmailAuthUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
  const rb = new RequestBuilder(rootUrl, getGmailAuthUrl.PATH, 'get');
  if (params) {
    rb.query('scopes', params.scopes, {});
    rb.query('state', params.state, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseString>;
    })
  );
}

getGmailAuthUrl.PATH = '/api/auth/oauth/google/auth-url';
