/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultAccountDetailDto } from '../../models/success-response-paged-result-account-detail-dto';

export interface ListSelfAccounts$Params {
  pageIndex: number;
  pageSize: number;
  status?: Array<'ACTIVE' | 'CLOSED'>;
  type?: Array<'PRINCIPAL' | 'GENERAL' | 'DONATION' | 'PUBLIC_DONATION' | 'WALLET'>;
  accountHolderId?: string;
  accountHolderName?: string;
  includePaymentDetail?: 'Y' | 'N';
  includeBalance?: 'Y' | 'N';
  accountId?: string;
}

export function listSelfAccounts(http: HttpClient, rootUrl: string, params: ListSelfAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultAccountDetailDto>> {
  const rb = new RequestBuilder(rootUrl, listSelfAccounts.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('accountHolderId', params.accountHolderId, {});
    rb.query('accountHolderName', params.accountHolderName, {});
    rb.query('includePaymentDetail', params.includePaymentDetail, {});
    rb.query('includeBalance', params.includeBalance, {});
    rb.query('accountId', params.accountId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultAccountDetailDto>;
    })
  );
}

listSelfAccounts.PATH = '/api/account/list/me';
