/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReverseTransactionDto } from '../../models/reverse-transaction-dto';
import { SuccessResponseTransactionDetailDto } from '../../models/success-response-transaction-detail-dto';

export interface ReverseTransaction$Params {
  id: string;
      body: ReverseTransactionDto
}

export function reverseTransaction(http: HttpClient, rootUrl: string, params: ReverseTransaction$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseTransactionDetailDto>> {
  const rb = new RequestBuilder(rootUrl, reverseTransaction.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseTransactionDetailDto>;
    })
  );
}

reverseTransaction.PATH = '/api/account/{id}/transaction/reverse';
