/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventDetail } from '../../models/event-detail';
import { SuccessResponseEventDetail } from '../../models/success-response-event-detail';

export interface UpdateSocialEvent$Params {
  id: string;
  'Correlation-Id'?: string;
      body: EventDetail
}

export function updateSocialEvent(http: HttpClient, rootUrl: string, params: UpdateSocialEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseEventDetail>> {
  const rb = new RequestBuilder(rootUrl, updateSocialEvent.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('Correlation-Id', params['Correlation-Id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseEventDetail>;
    })
  );
}

updateSocialEvent.PATH = '/api/socialevent/updateEvent/{id}';
