/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseQueueStatistics } from '../../models/success-response-queue-statistics';

export interface GetPerformanceMetrics$Params {
}

export function getPerformanceMetrics(http: HttpClient, rootUrl: string, params?: GetPerformanceMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseQueueStatistics>> {
  const rb = new RequestBuilder(rootUrl, getPerformanceMetrics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseQueueStatistics>;
    })
  );
}

getPerformanceMetrics.PATH = '/api/jobs/statistics';
