/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseString } from '../../models/success-response-string';

export interface QueueOperation$Params {

/**
 * Operation to trigger
 */
  operation: 'pause' | 'resume';
}

export function queueOperation(http: HttpClient, rootUrl: string, params: QueueOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
  const rb = new RequestBuilder(rootUrl, queueOperation.PATH, 'post');
  if (params) {
    rb.path('operation', params.operation, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseString>;
    })
  );
}

queueOperation.PATH = '/api/jobs/queue/{operation}';
