/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseReportDetailDto } from '../../models/success-response-report-detail-dto';

export interface ApproveReport$Params {

/**
 * The ID of the report to approve
 */
  reportId: string;
}

export function approveReport(http: HttpClient, rootUrl: string, params: ApproveReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseReportDetailDto>> {
  const rb = new RequestBuilder(rootUrl, approveReport.PATH, 'post');
  if (params) {
    rb.path('reportId', params.reportId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseReportDetailDto>;
    })
  );
}

approveReport.PATH = '/api/report/{reportId}/approve';
