/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseString } from '../../models/success-response-string';

export interface DeleteReport$Params {

/**
 * The ID of the report to delete
 */
  reportId: string;
}

export function deleteReport(http: HttpClient, rootUrl: string, params: DeleteReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseString>> {
  const rb = new RequestBuilder(rootUrl, deleteReport.PATH, 'delete');
  if (params) {
    rb.path('reportId', params.reportId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseString>;
    })
  );
}

deleteReport.PATH = '/api/report/{reportId}';
