/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultReportDetailDto } from '../../models/success-response-paged-result-report-detail-dto';

export interface ListReports$Params {

/**
 * The unique code of the report
 */
  reportCode: string;
  pageIndex?: number;
  pageSize?: number;

/**
 * Filter by report status
 */
  status?: 'DRAFT' | 'APPROVED';

/**
 * Filter by requester user ID
 */
  requestedById?: string;
}

export function listReports(http: HttpClient, rootUrl: string, params: ListReports$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultReportDetailDto>> {
  const rb = new RequestBuilder(rootUrl, listReports.PATH, 'get');
  if (params) {
    rb.path('reportCode', params.reportCode, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('status', params.status, {});
    rb.query('requestedById', params.requestedById, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultReportDetailDto>;
    })
  );
}

listReports.PATH = '/api/report/list/{reportCode}';
