/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultDonationDto } from '../../models/success-response-paged-result-donation-dto';

export interface ListGuestDonations$Params {
  pageIndex: number;
  pageSize: number;
  donorId?: string;
  status?: Array<'RAISED' | 'PAID' | 'PENDING' | 'PAYMENT_FAILED' | 'PAY_LATER' | 'CANCELLED' | 'UPDATE_MISTAKE'>;
  type?: Array<'REGULAR' | 'ONETIME'>;
  isGuest?: 'Y' | 'N';
  startDate?: string;
  endDate?: string;
  donationId?: string;
  donorName?: string;
}

export function listGuestDonations(http: HttpClient, rootUrl: string, params: ListGuestDonations$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultDonationDto>> {
  const rb = new RequestBuilder(rootUrl, listGuestDonations.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('donorId', params.donorId, {});
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('isGuest', params.isGuest, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('donationId', params.donationId, {});
    rb.query('donorName', params.donorName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultDonationDto>;
    })
  );
}

listGuestDonations.PATH = '/api/donation/list/guest';
