/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GenerateReport$Params {

/**
 * Report name
 */
  reportName: string;
  startDate?: string;
  endDate?: string;
  uploadFile?: 'Y' | 'N';
  sendEmail?: 'Y' | 'N';

/**
 * Date on which the report should be generated
 */
  on?: 'paidOn' | 'confirmedOn';
}

export function generateReport(http: HttpClient, rootUrl: string, params: GenerateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, generateReport.PATH, 'get');
  if (params) {
    rb.path('reportName', params.reportName, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('uploadFile', params.uploadFile, {});
    rb.query('sendEmail', params.sendEmail, {});
    rb.query('on', params.on, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

generateReport.PATH = '/api/finance-report/generate/{reportName}';
