/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseUserDto } from '../../models/success-response-user-dto';

export interface UserControllerGetLoggedInUser$Params {
}

export function userControllerGetLoggedInUser(http: HttpClient, rootUrl: string, params?: UserControllerGetLoggedInUser$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserDto>> {
  const rb = new RequestBuilder(rootUrl, userControllerGetLoggedInUser.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseUserDto>;
    })
  );
}

userControllerGetLoggedInUser.PATH = '/api/users/profile/me';
