/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateEarningDto } from '../../models/create-earning-dto';
import { SuccessResponseEarningDetailDto } from '../../models/success-response-earning-detail-dto';

export interface CreateEarning$Params {
      body: CreateEarningDto
}

export function createEarning(http: HttpClient, rootUrl: string, params: CreateEarning$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseEarningDetailDto>> {
  const rb = new RequestBuilder(rootUrl, createEarning.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseEarningDetailDto>;
    })
  );
}

createEarning.PATH = '/api/earning/create';
