/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultEarningDetailDto } from '../../models/success-response-paged-result-earning-detail-dto';

export interface ListSelfEarnings$Params {
  pageIndex: number;
  pageSize: number;
  status?: Array<'PENDING' | 'RECEIVED' | 'CANCELLED'>;
  category?: Array<'SERVICE' | 'PRODUCT' | 'GRANT' | 'SPONSORSHIP' | 'OTHER'>;
  source?: string;
  referenceId?: string;
  startDate?: string;
  endDate?: string;
}

export function listSelfEarnings(http: HttpClient, rootUrl: string, params: ListSelfEarnings$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultEarningDetailDto>> {
  const rb = new RequestBuilder(rootUrl, listSelfEarnings.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('status', params.status, {});
    rb.query('category', params.category, {});
    rb.query('source', params.source, {});
    rb.query('referenceId', params.referenceId, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultEarningDetailDto>;
    })
  );
}

listSelfEarnings.PATH = '/api/earning/list/me';
