/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseEarningDetailDto } from '../../models/success-response-earning-detail-dto';
import { UpdateEarningDto } from '../../models/update-earning-dto';

export interface UpdateEarning$Params {
  id: string;
      body: UpdateEarningDto
}

export function updateEarning(http: HttpClient, rootUrl: string, params: UpdateEarning$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseEarningDetailDto>> {
  const rb = new RequestBuilder(rootUrl, updateEarning.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseEarningDetailDto>;
    })
  );
}

updateEarning.PATH = '/api/earning/{id}/update';
