export const AppRoute = {
  welcome_page: {
    id: 'welcome_page',
    url: '',
    parent: '',
    feature: '',
    path: '',
  },
  login_page: {
    id: 'welcome_page',
    url: '/login',
    parent: '',
    feature: '',
    path: 'login',
  },
  login_callback_page: {
    id: 'login_callback_page',
    url: '/callback',
    parent: '',
    feature: '',
    path: 'callback',
  },
  secured_dashboard_page: {
    id: 'secured_dashboard_page',
    url: '/secured/dashboard',
    parent: 'secured',
    feature: 'dashboard',
    path: '',
  },
  secured_help_home_page: {
    id: 'secured_help_home_page',
    url: '/secured/help',
    parent: 'secured',
    feature: 'help',
    path: '',
  },
  secured_help_article_page: {
    id: 'secured_help_article_page',
    url: '/secured/help/:slug',
    parent: 'secured',
    feature: 'help',
    path: ':slug',
  },
  secured_finance_hub_page: {
    id: 'secured_finance_hub_page',
    url: '/secured/finance',
    parent: 'secured',
    feature: 'finance',
    path: '',
  },
  secured_donation_dashboard_page: {
    id: 'secured_donation_dashboard_page',
    url: '/secured/finance/donations',
    parent: 'secured',
    feature: 'finance',
    path: 'donations',
  },
  secured_donor_dashboard_page: {
    id: 'secured_donor_dashboard_page',
    url: '/secured/finance/donors',
    parent: 'secured',
    feature: 'finance',
    path: 'donors',
  },
  secured_finance_reports_page: {
    id: 'secured_finance_reports_page',
    url: '/secured/finance/reports',
    parent: 'secured',
    feature: 'finance',
    path: 'reports',
  },
  secured_donation_bulk_edit_page: {
    id: 'secured_donation_bulk_edit_page',
    url: '/secured/finance/donations/bulk-edit',
    parent: 'secured',
    feature: 'finance',
    path: 'donations/bulk-edit',
  },
  secured_member_members_page: {
    id: 'secured_member_members_page',
    url: '/secured/member/list',
    parent: 'secured',
    feature: 'member',
    path: 'list',
  },
  secured_member_profile_page: {
    id: 'secured_member_profile_page',
    url: '/secured/member', // /:id to be added dynamically
    parent: 'secured',
    feature: 'member',
    path: ':id',
  },
  secured_member_my_profile_page: {
    id: 'secured_member_my_profile_page',
    url: '/secured/member/myprofile',
    parent: 'secured',
    feature: 'member',
    path: 'myprofile',
  },
  secured_member_complete_my_profile_page: {
    id: 'secured_member_complete_my_profile_page',
    url: '/secured/member/completemyprofile',
    parent: 'secured',
    feature: 'member',
    path: 'completemyprofile',
  },
  secured_request_list_page: {
    id: 'secured_request_list_page',
    url: '/secured/workflow/requests',
    parent: 'secured',
    feature: 'workflow',
    path: 'requests',
  },
  secured_account_list_page: {
    id: 'secured_account_list_page',
    url: '/secured/finance/accounts',
    parent: 'secured',
    feature: 'finance',
    path: 'accounts',
  },
  secured_manage_account_page: {
    id: 'secured_manage_account_page',
    url: '/secured/finance/expenses',
    parent: 'secured',
    feature: 'finance',
    path: 'expenses',
  },
  secured_account_transaction_page: {
    id: 'secured_account_transaction_page',
    url: '/secured/finance/account/:id/transactions',
    parent: 'secured',
    feature: 'finance',
    path: 'account/:id/transactions',
  },
  secured_earning_dashboard_page: {
    id: 'secured_earning_dashboard_page',
    url: '/secured/finance/earnings',
    parent: 'secured',
    feature: 'finance',
    path: 'earnings',
  },
  secured_earning_form_create_page: {
    id: 'secured_earning_form_create_page',
    url: '/secured/finance/earnings/new',
    parent: 'secured',
    feature: 'finance',
    path: 'earnings/new',
  },
  secured_earning_form_edit_page: {
    id: 'secured_earning_form_edit_page',
    url: '/secured/finance/earnings/:id/edit',
    parent: 'secured',
    feature: 'finance',
    path: 'earnings/:id/edit',
  },
  secured_admin_hub_page: {
    id: 'secured_admin_hub_page',
    url: '/secured/admin',
    parent: 'secured',
    feature: 'admin',
    path: '',
  },
  secured_admin_dashboard_page: {
    id: 'secured_admin_dashboard_page',
    url: '/secured/admin/dashboard',
    parent: 'secured',
    feature: 'admin',
    path: 'dashboard',
  },
  secured_admin_api_keys_page: {
    id: 'secured_admin_api_keys_page',
    url: '/secured/admin/api-keys',
    parent: 'secured',
    feature: 'admin',
    path: 'api-keys',
  },
  secured_admin_oauth_page: {
    id: 'secured_admin_oauth_page',
    url: '/secured/admin/oauth',
    parent: 'secured',
    feature: 'admin',
    path: 'oauth',
  },
  secured_admin_jobs_page: {
    id: 'secured_admin_jobs_page',
    url: '/secured/admin/jobs',
    parent: 'secured',
    feature: 'admin',
    path: 'jobs',
  },
  secured_admin_cron_jobs_page: {
    id: 'secured_admin_cron_jobs_page',
    url: '/secured/admin/cron-jobs',
    parent: 'secured',
    feature: 'admin',
    path: 'cron-jobs',
  },
  secured_admin_notifications_page: {
    id: 'secured_admin_notifications_page',
    url: '/secured/admin/notifications',
    parent: 'secured',
    feature: 'admin',
    path: 'notifications',
  },
  secured_admin_roles_page: {
    id: 'secured_admin_roles_page',
    url: '/secured/admin/roles',
    parent: 'secured',
    feature: 'admin',
    path: 'roles',
  },
  secured_admin_json_store_page: {
    id: 'secured_admin_json_store_page',
    url: '/secured/admin/json-store',
    parent: 'secured',
    feature: 'admin',
    path: 'json-store',
  },
  secured_admin_master_data_page: {
    id: 'secured_admin_master_data_page',
    url: '/secured/admin/master-data/:namespace',
    parent: 'secured',
    feature: 'admin',
    path: 'master-data/:namespace',
  },
  secured_admin_links_page: {
    id: 'secured_admin_links_page',
    url: '/secured/admin/links',
    parent: 'secured',
    feature: 'admin',
    path: 'links',
  },
  secured_admin_help_portal_page: {
    id: 'secured_admin_help_portal_page',
    url: '/secured/admin/help-portal',
    parent: 'secured',
    feature: 'admin',
    path: 'help-portal',
  },
  secured_admin_email_templates_page: {
    id: 'secured_admin_email_templates_page',
    url: '/secured/admin/email-templates',
    parent: 'secured',
    feature: 'admin',
    path: 'email-templates',
  },
  secured_admin_public_site_page: {
    id: 'secured_admin_public_site_page',
    url: '/secured/admin/public-site',
    parent: 'secured',
    feature: 'admin',
    path: 'public-site',
  },
  secured_admin_custom_forms_page: {
    id: 'secured_admin_custom_forms_page',
    url: '/secured/admin/custom-forms',
    parent: 'secured',
    feature: 'admin',
    path: 'custom-forms',
  },
  secured_event_list_page: {
    id: 'secured_event_list_page',
    url: '/secured/socialevents/list',
    parent: 'secured',
    feature: 'socialevents',
    path: 'list'
  },
  secured_project_hub_page: {
    id: 'secured_project_hub_page',
    url: '/secured/project',
    parent: 'secured',
    feature: 'project',
    path: ''
  },
  secured_project_list_page: {
    id: 'secured_project_list_page',
    url: '/secured/project/projects',
    parent: 'secured',
    feature: 'project',
    path: 'projects'
  },
  secured_project_reports_page: {
    id: 'secured_project_reports_page',
    url: '/secured/project/reports',
    parent: 'secured',
    feature: 'project',
    path: 'reports'
  },
  secured_project_activities_page: {
    id: 'secured_project_activities_page',
    url: '/secured/project/activities',
    parent: 'secured',
    feature: 'project',
    path: 'activities'
  },
  secured_project_goals_page: {
    id: 'secured_project_goals_page',
    url: '/secured/project/goals',
    parent: 'secured',
    feature: 'project',
    path: 'goals'
  },
  secured_project_beneficiaries_page: {
    id: 'secured_project_beneficiaries_page',
    url: '/secured/project/beneficiaries',
    parent: 'secured',
    feature: 'project',
    path: 'beneficiaries'
  },
  secured_project_milestones_page: {
    id: 'secured_project_milestones_page',
    url: '/secured/project/milestones',
    parent: 'secured',
    feature: 'project',
    path: 'milestones'
  },
  secured_project_team_page: {
    id: 'secured_project_team_page',
    url: '/secured/project/team',
    parent: 'secured',
    feature: 'project',
    path: 'team'
  },
  secured_project_risks_page: {
    id: 'secured_project_risks_page',
    url: '/secured/project/risks',
    parent: 'secured',
    feature: 'project',
    path: 'risks'
  },
  secured_meetings_list_page: {
    id: 'secured_meetings_list_page',
    url: '/secured/communication/meetings',
    parent: 'secured',
    feature: 'communication',
    path: 'meetings'
  },
  secured_assets_hub_page: {
    id: 'secured_assets_hub_page',
    url: '/secured/assets',
    parent: 'secured',
    feature: 'assets',
    path: ''
  },
  secured_assets_list_page: {
    id: 'secured_assets_list_page',
    url: '/secured/assets/list',
    parent: 'secured',
    feature: 'assets',
    path: 'list'
  },
  secured_books_list_page: {
    id: 'secured_books_list_page',
    url: '/secured/assets/books',
    parent: 'secured',
    feature: 'assets',
    path: 'books'
  },
};
