/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkNotificationDto } from '../../models/bulk-notification-dto';
import { SuccessResponseNotificationResponseDto } from '../../models/success-response-notification-response-dto';

export interface CreateBulkNotifications$Params {
      body: BulkNotificationDto
}

export function createBulkNotifications(http: HttpClient, rootUrl: string, params: CreateBulkNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseNotificationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createBulkNotifications.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseNotificationResponseDto>;
    })
  );
}

createBulkNotifications.PATH = '/api/notifications/bulk';
