/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseNotificationResponseDto } from '../../models/success-response-notification-response-dto';

export interface GetMyNotifications$Params {
  pageIndex?: number;
  pageSize?: number;
  type?: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'TASK' | 'APPROVAL' | 'REMINDER' | 'ANNOUNCEMENT';
  category?: 'SYSTEM' | 'WORKFLOW' | 'DONATION' | 'EXPENSE' | 'PROJECT' | 'MEETING' | 'TASK' | 'DOCUMENT';
  isRead?: 'Y' | 'N';
  isArchived?: 'Y' | 'N';
  referenceId?: string;
  referenceType?: string;
  fromDate?: string;
  toDate?: string;
}

export function getMyNotifications(http: HttpClient, rootUrl: string, params?: GetMyNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseNotificationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getMyNotifications.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('type', params.type, {});
    rb.query('category', params.category, {});
    rb.query('isRead', params.isRead, {});
    rb.query('isArchived', params.isArchived, {});
    rb.query('referenceId', params.referenceId, {});
    rb.query('referenceType', params.referenceType, {});
    rb.query('fromDate', params.fromDate, {});
    rb.query('toDate', params.toDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseNotificationResponseDto>;
    })
  );
}

getMyNotifications.PATH = '/api/notifications/me';
