/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseSuccessResponse } from '../../models/success-response-success-response';

export interface RunScheduledJob$Params {
  name: string;
}

export function runScheduledJob(http: HttpClient, rootUrl: string, params: RunScheduledJob$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseSuccessResponse>> {
  const rb = new RequestBuilder(rootUrl, runScheduledJob.PATH, 'post');
  if (params) {
    rb.path('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseSuccessResponse>;
    })
  );
}

runScheduledJob.PATH = '/api/cron/run/{name}';
