/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseArrayKeyValueDto } from '../../models/success-response-array-key-value-dto';

export interface GetStaticLinks$Params {

/**
 * Type of app links
 */
  linkType: string;
}

export function getStaticLinks(http: HttpClient, rootUrl: string, params: GetStaticLinks$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayKeyValueDto>> {
  const rb = new RequestBuilder(rootUrl, getStaticLinks.PATH, 'get');
  if (params) {
    rb.query('linkType', params.linkType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseArrayKeyValueDto>;
    })
  );
}

getStaticLinks.PATH = '/api/static-docs/app-links';
