/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseUserRefDataDto } from '../../models/success-response-user-ref-data-dto';

export interface ReferenceData$Params {
  countryCode?: string;
  stateCode?: string;
}

export function referenceData(http: HttpClient, rootUrl: string, params?: ReferenceData$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserRefDataDto>> {
  const rb = new RequestBuilder(rootUrl, referenceData.PATH, 'get');
  if (params) {
    rb.query('countryCode', params.countryCode, {});
    rb.query('stateCode', params.stateCode, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseUserRefDataDto>;
    })
  );
}

referenceData.PATH = '/api/users/referenceData';
