/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseUserDto } from '../../models/success-response-user-dto';
import { UserUpdateDto } from '../../models/user-update-dto';

export interface UpdateMyDetails$Params {
      body: UserUpdateDto
}

export function updateMyDetails(http: HttpClient, rootUrl: string, params: UpdateMyDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseUserDto>> {
  const rb = new RequestBuilder(rootUrl, updateMyDetails.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseUserDto>;
    })
  );
}

updateMyDetails.PATH = '/api/users/profile/me';
