/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StartWorkflowDto } from '../../models/start-workflow-dto';
import { SuccessResponseWorkflowInstanceDto } from '../../models/success-response-workflow-instance-dto';

export interface WorkflowControllerStartWorkflow$Params {
      body: StartWorkflowDto
}

export function workflowControllerStartWorkflow(http: HttpClient, rootUrl: string, params: WorkflowControllerStartWorkflow$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, workflowControllerStartWorkflow.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseWorkflowInstanceDto>;
    })
  );
}

workflowControllerStartWorkflow.PATH = '/api/workflows/create';
