/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseWorkflowInstanceDto } from '../../models/success-response-workflow-instance-dto';

export interface WorkflowControllerGetInstance$Params {
  id: string;
}

export function workflowControllerGetInstance(http: HttpClient, rootUrl: string, params: WorkflowControllerGetInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, workflowControllerGetInstance.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseWorkflowInstanceDto>;
    })
  );
}

workflowControllerGetInstance.PATH = '/api/workflows/{id}/instances';
