/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseWorkflowTaskDto } from '../../models/success-response-workflow-task-dto';
import { UpdateTaskDto } from '../../models/update-task-dto';

export interface WorkflowControllerUpdateTask$Params {
  id: string;
  taskId: string;
      body: UpdateTaskDto
}

export function workflowControllerUpdateTask(http: HttpClient, rootUrl: string, params: WorkflowControllerUpdateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowTaskDto>> {
  const rb = new RequestBuilder(rootUrl, workflowControllerUpdateTask.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('taskId', params.taskId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseWorkflowTaskDto>;
    })
  );
}

workflowControllerUpdateTask.PATH = '/api/workflows/{id}/tasks/{taskId}/update';
