/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseArrayCommentResponseDto } from '../../models/success-response-array-comment-response-dto';

export interface GetComments$Params {
  entityType: string;
  entityId: string;
}

export function getComments(http: HttpClient, rootUrl: string, params: GetComments$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayCommentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getComments.PATH, 'get');
  if (params) {
    rb.query('entityType', params.entityType, {});
    rb.query('entityId', params.entityId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseArrayCommentResponseDto>;
    })
  );
}

getComments.PATH = '/api/comments';
