/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SendEmailDto } from '../../models/send-email-dto';
import { SuccessResponseSendEmailResult } from '../../models/success-response-send-email-result';

export interface SendEmail$Params {
      body: SendEmailDto
}

export function sendEmail(http: HttpClient, rootUrl: string, params: SendEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseSendEmailResult>> {
  const rb = new RequestBuilder(rootUrl, sendEmail.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseSendEmailResult>;
    })
  );
}

sendEmail.PATH = '/api/correspondence/send-email';
