/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultWorkflowInstanceDto } from '../../models/success-response-paged-result-workflow-instance-dto';

export interface ListInstancesForMe$Params {

/**
 * Index of the page to retrieve
 */
  pageIndex?: number;

/**
 * Count of content to load per page
 */
  pageSize?: number;
  workflowId?: string;
  status?: Array<'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED' | 'CANCELLED'>;
  type?: Array<string>;
  delegated?: 'Y' | 'N';
}

export function listInstancesForMe(http: HttpClient, rootUrl: string, params?: ListInstancesForMe$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, listInstancesForMe.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('workflowId', params.workflowId, {});
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('delegated', params.delegated, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>;
    })
  );
}

listInstancesForMe.PATH = '/api/workflows/instances/forMe';
