/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultWorkflowInstanceDto } from '../../models/success-response-paged-result-workflow-instance-dto';

export interface ListInstancesByMe$Params {

/**
 * Index of the page to retrieve
 */
  page?: number;

/**
 * Count of content to load per page
 */
  size?: number;

/**
 * Filter by delegated (set true to get workflow created by me for others, set false to get only workflow created by me for me)
 */
  delegated?: boolean;
}

export function listInstancesByMe(http: HttpClient, rootUrl: string, params?: ListInstancesByMe$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, listInstancesByMe.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('delegated', params.delegated, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultWorkflowInstanceDto>;
    })
  );
}

listInstancesByMe.PATH = '/api/workflows/instances/byMe';
