/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultWorkflowTaskDto } from '../../models/success-response-paged-result-workflow-task-dto';

export interface ListTasks$Params {

/**
 * Index of the page to retrieve
 */
  page?: number;

/**
 * Count of content to load per page
 */
  size?: number;
}

export function listTasks(http: HttpClient, rootUrl: string, params?: ListTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultWorkflowTaskDto>> {
  const rb = new RequestBuilder(rootUrl, listTasks.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultWorkflowTaskDto>;
    })
  );
}

listTasks.PATH = '/api/workflows/tasks/forMe';
