/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseWorkflowInstanceDto } from '../../models/success-response-workflow-instance-dto';

export interface ReassignTask$Params {
  id: string;
  taskId: string;

/**
 * Reassign based on workflow definition roles
 */
  fromDefinition?: boolean;

/**
 * User ID to reassign the task to
 */
  userId?: string;
}

export function reassignTask(http: HttpClient, rootUrl: string, params: ReassignTask$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, reassignTask.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('taskId', params.taskId, {});
    rb.query('fromDefinition', params.fromDefinition, {});
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseWorkflowInstanceDto>;
    })
  );
}

reassignTask.PATH = '/api/workflows/{id}/tasks/{taskId}/reassign';
