/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { JobControllerService } from './services/job-controller.service';
import { UserControllerService } from './services/user-controller.service';
import { OAuthControllerService } from './services/o-auth-controller.service';
import { ApiKeyControllerService } from './services/api-key-controller.service';
import { WorkflowControllerService } from './services/workflow-controller.service';
import { DonationControllerService } from './services/donation-controller.service';
import { AccountControllerService } from './services/account-controller.service';
import { ExpenseControllerService } from './services/expense-controller.service';
import { FinanceReportControllerService } from './services/finance-report-controller.service';
import { DmsControllerService } from './services/dms-controller.service';
import { StaticDocsControllerService } from './services/static-docs-controller.service';
import { PublicControllerService } from './services/public-controller.service';
import { CallbackControllerService } from './services/callback-controller.service';
import { HealthControllerService } from './services/health-controller.service';
import { ProjectControllerService } from './services/project-controller.service';
import { CorrespondenceControllerService } from './services/correspondence-controller.service';
import { MeetingControllerService } from './services/meeting-controller.service';
import { CronControllerService } from './services/cron-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    JobControllerService,
    UserControllerService,
    OAuthControllerService,
    ApiKeyControllerService,
    WorkflowControllerService,
    DonationControllerService,
    AccountControllerService,
    ExpenseControllerService,
    FinanceReportControllerService,
    DmsControllerService,
    StaticDocsControllerService,
    PublicControllerService,
    CallbackControllerService,
    HealthControllerService,
    ProjectControllerService,
    CorrespondenceControllerService,
    MeetingControllerService,
    CronControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
