/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { JobMonitoringService } from './services/job-monitoring.service';
import { UserService } from './services/user.service';
import { OAuthService } from './services/o-auth.service';
import { ApiKeyService } from './services/api-key.service';
import { WorkflowsService } from './services/workflows.service';
import { DonationsService } from './services/donations.service';
import { DmsService } from './services/dms.service';
import { PublicService } from './services/public.service';
import { HealthService } from './services/health.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    JobMonitoringService,
    UserService,
    OAuthService,
    ApiKeyService,
    WorkflowsService,
    DonationsService,
    DmsService,
    PublicService,
    HealthService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
