/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { sendEmail } from '../fn/correspondence-controller/send-email';
import { SendEmail$Params } from '../fn/correspondence-controller/send-email';
import { SuccessResponseSendEmailResult } from '../models/success-response-send-email-result';

@Injectable({ providedIn: 'root' })
export class CorrespondenceControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `sendEmail()` */
  static readonly SendEmailPath = '/api/correspondence/send-email';

  /**
   * Send email.
   *
   * **Required Permissions:**
   * - `create:send_email`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendEmail$Response(params: SendEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseSendEmailResult>> {
    return sendEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * Send email.
   *
   * **Required Permissions:**
   * - `create:send_email`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendEmail(params: SendEmail$Params, context?: HttpContext): Observable<SuccessResponseSendEmailResult> {
    return this.sendEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseSendEmailResult>): SuccessResponseSendEmailResult => r.body)
    );
  }

}
