/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEarning } from '../fn/earning-controller/create-earning';
import { CreateEarning$Params } from '../fn/earning-controller/create-earning';
import { getEarningById } from '../fn/earning-controller/get-earning-by-id';
import { GetEarningById$Params } from '../fn/earning-controller/get-earning-by-id';
import { listEarnings } from '../fn/earning-controller/list-earnings';
import { ListEarnings$Params } from '../fn/earning-controller/list-earnings';
import { listSelfEarnings } from '../fn/earning-controller/list-self-earnings';
import { ListSelfEarnings$Params } from '../fn/earning-controller/list-self-earnings';
import { SuccessResponseEarningDetailDto } from '../models/success-response-earning-detail-dto';
import { SuccessResponsePagedResultEarningDetailDto } from '../models/success-response-paged-result-earning-detail-dto';
import { updateEarning } from '../fn/earning-controller/update-earning';
import { UpdateEarning$Params } from '../fn/earning-controller/update-earning';

@Injectable({ providedIn: 'root' })
export class EarningControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createEarning()` */
  static readonly CreateEarningPath = '/api/earning/create';

  /**
   * Create new earning.
   *
   * **Required Permissions:**
   * - `create:earning`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEarning()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEarning$Response(params: CreateEarning$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseEarningDetailDto>> {
    return createEarning(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new earning.
   *
   * **Required Permissions:**
   * - `create:earning`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEarning$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEarning(params: CreateEarning$Params, context?: HttpContext): Observable<SuccessResponseEarningDetailDto> {
    return this.createEarning$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseEarningDetailDto>): SuccessResponseEarningDetailDto => r.body)
    );
  }

  /** Path part for operation `updateEarning()` */
  static readonly UpdateEarningPath = '/api/earning/{id}/update';

  /**
   * Update earning details.
   *
   * **Required Permissions:**
   * - `update:earning`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEarning()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEarning$Response(params: UpdateEarning$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseEarningDetailDto>> {
    return updateEarning(this.http, this.rootUrl, params, context);
  }

  /**
   * Update earning details.
   *
   * **Required Permissions:**
   * - `update:earning`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEarning$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEarning(params: UpdateEarning$Params, context?: HttpContext): Observable<SuccessResponseEarningDetailDto> {
    return this.updateEarning$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseEarningDetailDto>): SuccessResponseEarningDetailDto => r.body)
    );
  }

  /** Path part for operation `listEarnings()` */
  static readonly ListEarningsPath = '/api/earning/list';

  /**
   * List all earnings.
   *
   * **Required Permissions:**
   * - `read:earning`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listEarnings()` instead.
   *
   * This method doesn't expect any request body.
   */
  listEarnings$Response(params: ListEarnings$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultEarningDetailDto>> {
    return listEarnings(this.http, this.rootUrl, params, context);
  }

  /**
   * List all earnings.
   *
   * **Required Permissions:**
   * - `read:earning`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listEarnings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listEarnings(params: ListEarnings$Params, context?: HttpContext): Observable<SuccessResponsePagedResultEarningDetailDto> {
    return this.listEarnings$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultEarningDetailDto>): SuccessResponsePagedResultEarningDetailDto => r.body)
    );
  }

  /** Path part for operation `listSelfEarnings()` */
  static readonly ListSelfEarningsPath = '/api/earning/list/me';

  /**
   * List own earnings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listSelfEarnings()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfEarnings$Response(params: ListSelfEarnings$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultEarningDetailDto>> {
    return listSelfEarnings(this.http, this.rootUrl, params, context);
  }

  /**
   * List own earnings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listSelfEarnings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSelfEarnings(params: ListSelfEarnings$Params, context?: HttpContext): Observable<SuccessResponsePagedResultEarningDetailDto> {
    return this.listSelfEarnings$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultEarningDetailDto>): SuccessResponsePagedResultEarningDetailDto => r.body)
    );
  }

  /** Path part for operation `getEarningById()` */
  static readonly GetEarningByIdPath = '/api/earning/{id}';

  /**
   * Get earning by ID.
   *
   * **Required Permissions:**
   * - `read:earning`
   * _(Any of these permissions)_
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEarningById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEarningById$Response(params: GetEarningById$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseEarningDetailDto>> {
    return getEarningById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get earning by ID.
   *
   * **Required Permissions:**
   * - `read:earning`
   * _(Any of these permissions)_
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEarningById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEarningById(params: GetEarningById$Params, context?: HttpContext): Observable<SuccessResponseEarningDetailDto> {
    return this.getEarningById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseEarningDetailDto>): SuccessResponseEarningDetailDto => r.body)
    );
  }

}
