/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createActivity } from '../fn/project-controller/create-activity';
import { CreateActivity$Params } from '../fn/project-controller/create-activity';
import { createProject } from '../fn/project-controller/create-project';
import { CreateProject$Params } from '../fn/project-controller/create-project';
import { getProjectById } from '../fn/project-controller/get-project-by-id';
import { GetProjectById$Params } from '../fn/project-controller/get-project-by-id';
import { getProjectReferenceData } from '../fn/project-controller/get-project-reference-data';
import { GetProjectReferenceData$Params } from '../fn/project-controller/get-project-reference-data';
import { listActivities } from '../fn/project-controller/list-activities';
import { ListActivities$Params } from '../fn/project-controller/list-activities';
import { listProjects } from '../fn/project-controller/list-projects';
import { ListProjects$Params } from '../fn/project-controller/list-projects';
import { SuccessResponseActivityDetailDto } from '../models/success-response-activity-detail-dto';
import { SuccessResponsePagedResultActivityDetailDto } from '../models/success-response-paged-result-activity-detail-dto';
import { SuccessResponsePagedResultProjectDetailDto } from '../models/success-response-paged-result-project-detail-dto';
import { SuccessResponseProjectDetailDto } from '../models/success-response-project-detail-dto';
import { SuccessResponseProjectRefDataDto } from '../models/success-response-project-ref-data-dto';
import { updateActivity } from '../fn/project-controller/update-activity';
import { UpdateActivity$Params } from '../fn/project-controller/update-activity';
import { updateProject } from '../fn/project-controller/update-project';
import { UpdateProject$Params } from '../fn/project-controller/update-project';

@Injectable({ providedIn: 'root' })
export class ProjectControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listProjects()` */
  static readonly ListProjectsPath = '/api/projects';

  /**
   * List projects with filters and pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  listProjects$Response(params?: ListProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultProjectDetailDto>> {
    return listProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * List projects with filters and pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listProjects(params?: ListProjects$Params, context?: HttpContext): Observable<SuccessResponsePagedResultProjectDetailDto> {
    return this.listProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultProjectDetailDto>): SuccessResponsePagedResultProjectDetailDto => r.body)
    );
  }

  /** Path part for operation `createProject()` */
  static readonly CreateProjectPath = '/api/projects/create';

  /**
   * Create a new project.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProject$Response(params: CreateProject$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseProjectDetailDto>> {
    return createProject(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new project.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProject(params: CreateProject$Params, context?: HttpContext): Observable<SuccessResponseProjectDetailDto> {
    return this.createProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseProjectDetailDto>): SuccessResponseProjectDetailDto => r.body)
    );
  }

  /** Path part for operation `updateProject()` */
  static readonly UpdateProjectPath = '/api/projects/{id}/update';

  /**
   * Update a project.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProject$Response(params: UpdateProject$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseProjectDetailDto>> {
    return updateProject(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a project.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProject(params: UpdateProject$Params, context?: HttpContext): Observable<SuccessResponseProjectDetailDto> {
    return this.updateProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseProjectDetailDto>): SuccessResponseProjectDetailDto => r.body)
    );
  }

  /** Path part for operation `getProjectById()` */
  static readonly GetProjectByIdPath = '/api/projects/{id}';

  /**
   * Get project by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectById$Response(params: GetProjectById$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseProjectDetailDto>> {
    return getProjectById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get project by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectById(params: GetProjectById$Params, context?: HttpContext): Observable<SuccessResponseProjectDetailDto> {
    return this.getProjectById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseProjectDetailDto>): SuccessResponseProjectDetailDto => r.body)
    );
  }

  /** Path part for operation `listActivities()` */
  static readonly ListActivitiesPath = '/api/projects/{id}/activities';

  /**
   * List project activities with filters and pagination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listActivities()` instead.
   *
   * This method doesn't expect any request body.
   */
  listActivities$Response(params: ListActivities$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultActivityDetailDto>> {
    return listActivities(this.http, this.rootUrl, params, context);
  }

  /**
   * List project activities with filters and pagination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listActivities$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listActivities(params: ListActivities$Params, context?: HttpContext): Observable<SuccessResponsePagedResultActivityDetailDto> {
    return this.listActivities$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponsePagedResultActivityDetailDto>): SuccessResponsePagedResultActivityDetailDto => r.body)
    );
  }

  /** Path part for operation `createActivity()` */
  static readonly CreateActivityPath = '/api/projects/{id}/activity';

  /**
   * create new activity.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createActivity()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createActivity$Response(params: CreateActivity$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseActivityDetailDto>> {
    return createActivity(this.http, this.rootUrl, params, context);
  }

  /**
   * create new activity.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createActivity$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createActivity(params: CreateActivity$Params, context?: HttpContext): Observable<SuccessResponseActivityDetailDto> {
    return this.createActivity$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseActivityDetailDto>): SuccessResponseActivityDetailDto => r.body)
    );
  }

  /** Path part for operation `updateActivity()` */
  static readonly UpdateActivityPath = '/api/projects/{id}/activity/{activityId}';

  /**
   * Update project activity.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateActivity()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateActivity$Response(params: UpdateActivity$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseActivityDetailDto>> {
    return updateActivity(this.http, this.rootUrl, params, context);
  }

  /**
   * Update project activity.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateActivity$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateActivity(params: UpdateActivity$Params, context?: HttpContext): Observable<SuccessResponseActivityDetailDto> {
    return this.updateActivity$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseActivityDetailDto>): SuccessResponseActivityDetailDto => r.body)
    );
  }

  /** Path part for operation `getProjectReferenceData()` */
  static readonly GetProjectReferenceDataPath = '/api/projects/static/referenceData';

  /**
   * Get project reference data.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectReferenceData()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectReferenceData$Response(params?: GetProjectReferenceData$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseProjectRefDataDto>> {
    return getProjectReferenceData(this.http, this.rootUrl, params, context);
  }

  /**
   * Get project reference data.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectReferenceData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectReferenceData(params?: GetProjectReferenceData$Params, context?: HttpContext): Observable<SuccessResponseProjectRefDataDto> {
    return this.getProjectReferenceData$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseProjectRefDataDto>): SuccessResponseProjectRefDataDto => r.body)
    );
  }

}
