/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { contactUs } from '../fn/public-controller/contact-us';
import { ContactUs$Params } from '../fn/public-controller/contact-us';
import { donate } from '../fn/public-controller/donate';
import { Donate$Params } from '../fn/public-controller/donate';
import { getCpntent } from '../fn/public-controller/get-cpntent';
import { GetCpntent$Params } from '../fn/public-controller/get-cpntent';
import { getTeam } from '../fn/public-controller/get-team';
import { GetTeam$Params } from '../fn/public-controller/get-team';
import { signUp } from '../fn/public-controller/sign-up';
import { SignUp$Params } from '../fn/public-controller/sign-up';

@Injectable({ providedIn: 'root' })
export class PublicControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTeam()` */
  static readonly GetTeamPath = '/api/public/team';

  /**
   * Get team members.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTeam()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeam$Response(params?: GetTeam$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
}>>> {
    return getTeam(this.http, this.rootUrl, params, context);
  }

  /**
   * Get team members.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTeam$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeam(params?: GetTeam$Params, context?: HttpContext): Observable<Array<{
}>> {
    return this.getTeam$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<{
}>>): Array<{
}> => r.body)
    );
  }

  /** Path part for operation `getCpntent()` */
  static readonly GetCpntentPath = '/api/public/content';

  /**
   * Get public content.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCpntent()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCpntent$Response(params?: GetCpntent$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getCpntent(this.http, this.rootUrl, params, context);
  }

  /**
   * Get public content.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCpntent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCpntent(params?: GetCpntent$Params, context?: HttpContext): Observable<{
}> {
    return this.getCpntent$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `contactUs()` */
  static readonly ContactUsPath = '/api/public/contact';

  /**
   * Submit contact form.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactUs()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactUs$Response(params: ContactUs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return contactUs(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit contact form.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactUs$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactUs(params: ContactUs$Params, context?: HttpContext): Observable<void> {
    return this.contactUs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `signUp()` */
  static readonly SignUpPath = '/api/public/signup';

  /**
   * Sign up.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `signUp()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  signUp$Response(params: SignUp$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return signUp(this.http, this.rootUrl, params, context);
  }

  /**
   * Sign up.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `signUp$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  signUp(params: SignUp$Params, context?: HttpContext): Observable<void> {
    return this.signUp$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `donate()` */
  static readonly DonatePath = '/api/public/donate';

  /**
   * Submit donation form.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `donate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  donate$Response(params: Donate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return donate(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit donation form.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `donate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  donate(params: Donate$Params, context?: HttpContext): Observable<void> {
    return this.donate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
