/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getPolicies } from '../fn/static-docs-controller/get-policies';
import { GetPolicies$Params } from '../fn/static-docs-controller/get-policies';
import { getUserGuides } from '../fn/static-docs-controller/get-user-guides';
import { GetUserGuides$Params } from '../fn/static-docs-controller/get-user-guides';
import { SuccessResponseArrayStaticDocumentDto } from '../models/success-response-array-static-document-dto';

@Injectable({ providedIn: 'root' })
export class StaticDocsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getUserGuides()` */
  static readonly GetUserGuidesPath = '/api/static-docs/user-guides';

  /**
   * Get user guides.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserGuides()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserGuides$Response(params?: GetUserGuides$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayStaticDocumentDto>> {
    return getUserGuides(this.http, this.rootUrl, params, context);
  }

  /**
   * Get user guides.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserGuides$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserGuides(params?: GetUserGuides$Params, context?: HttpContext): Observable<SuccessResponseArrayStaticDocumentDto> {
    return this.getUserGuides$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayStaticDocumentDto>): SuccessResponseArrayStaticDocumentDto => r.body)
    );
  }

  /** Path part for operation `getPolicies()` */
  static readonly GetPoliciesPath = '/api/static-docs/policies';

  /**
   * Get policies.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPolicies()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPolicies$Response(params?: GetPolicies$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayStaticDocumentDto>> {
    return getPolicies(this.http, this.rootUrl, params, context);
  }

  /**
   * Get policies.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPolicies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPolicies(params?: GetPolicies$Params, context?: HttpContext): Observable<SuccessResponseArrayStaticDocumentDto> {
    return this.getPolicies$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuccessResponseArrayStaticDocumentDto>): SuccessResponseArrayStaticDocumentDto => r.body)
    );
  }

}
