/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultUserDto } from '../../models/success-response-paged-result-user-dto';

export interface ListUsers$Params {

/**
 * Index of the page to retrieve
 */
  pageIndex?: number;

/**
 * Count of content to load per page
 */
  pageSize?: number;
  firstName?: string;
  lastName?: string;
  email?: string;
  status?: 'DRAFT' | 'ACTIVE' | 'BLOCKED';
  roleCodes?: Array<string>;
  phoneNumber?: string;
  public?: boolean;
}

export function listUsers(http: HttpClient, rootUrl: string, params?: ListUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultUserDto>> {
  const rb = new RequestBuilder(rootUrl, listUsers.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('firstName', params.firstName, {});
    rb.query('lastName', params.lastName, {});
    rb.query('email', params.email, {});
    rb.query('status', params.status, {});
    rb.query('roleCodes', params.roleCodes, {});
    rb.query('phoneNumber', params.phoneNumber, {});
    rb.query('public', params.public, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultUserDto>;
    })
  );
}

listUsers.PATH = '/api/users';
