/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateOneTimeDonationDto } from '../../models/create-one-time-donation-dto';
import { DonationDto } from '../../models/donation-dto';

export interface DonationControllerCreateOneTime$Params {
      body: CreateOneTimeDonationDto
}

export function donationControllerCreateOneTime(http: HttpClient, rootUrl: string, params: DonationControllerCreateOneTime$Params, context?: HttpContext): Observable<StrictHttpResponse<DonationDto>> {
  const rb = new RequestBuilder(rootUrl, donationControllerCreateOneTime.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DonationDto>;
    })
  );
}

donationControllerCreateOneTime.PATH = '/api/finance/donations/one-time';
