/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePagedResultProjectDetailDto } from '../../models/success-response-paged-result-project-detail-dto';

export interface ListProjects$Params {
  pageIndex?: number;
  pageSize?: number;
  status?: 'PLANNING' | 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
  category?: 'EDUCATION' | 'HEALTH' | 'ENVIRONMENT' | 'RURAL_DEVELOPMENT' | 'WOMEN_EMPOWERMENT' | 'CHILD_WELFARE' | 'DISASTER_RELIEF' | 'OTHER';
  phase?: 'INITIATION' | 'PLANNING' | 'EXECUTION' | 'MONITORING' | 'CLOSURE';
  managerId?: string;
  sponsorId?: string;
  location?: string;
  tags?: Array<string>;
}

export function listProjects(http: HttpClient, rootUrl: string, params?: ListProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePagedResultProjectDetailDto>> {
  const rb = new RequestBuilder(rootUrl, listProjects.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('status', params.status, {});
    rb.query('category', params.category, {});
    rb.query('phase', params.phase, {});
    rb.query('managerId', params.managerId, {});
    rb.query('sponsorId', params.sponsorId, {});
    rb.query('location', params.location, {});
    rb.query('tags', params.tags, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePagedResultProjectDetailDto>;
    })
  );
}

listProjects.PATH = '/api/projects';
