/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseArrayApiKeyDto } from '../../models/success-response-array-api-key-dto';

export interface ListApiKeys$Params {
}

export function listApiKeys(http: HttpClient, rootUrl: string, params?: ListApiKeys$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseArrayApiKeyDto>> {
  const rb = new RequestBuilder(rootUrl, listApiKeys.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseArrayApiKeyDto>;
    })
  );
}

listApiKeys.PATH = '/api/auth/apikey/list';
