/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponseNumber } from '../../models/success-response-number';

export interface GetMyUnreadCount$Params {
}

export function getMyUnreadCount(http: HttpClient, rootUrl: string, params?: GetMyUnreadCount$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseNumber>> {
  const rb = new RequestBuilder(rootUrl, getMyUnreadCount.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseNumber>;
    })
  );
}

getMyUnreadCount.PATH = '/api/notifications/me/unread/count';
