export const AppRoute = {
  welcome_page: {
    id: 'welcome_page',
    url: '',
    parent: '',
    feature: '',
    path: '',
  },
  login_page: {
    id: 'welcome_page',
    url: '/login',
    parent: '',
    feature: '',
    path: 'login',
  },
  login_callback_page: {
    id: 'login_callback_page',
    url: '/callback',
    parent: '',
    feature: '',
    path: 'callback',
  },
  secured_dashboard_page: {
    id: 'secured_dashboard_page',
    url: '/secured/dashboard',
    parent: 'secured',
    feature: 'dashboard',
    path: '',
  },
  secured_dashboard_help_page: {
    id: 'secured_dashboard_help_page',
    url: '/secured/dashboard/help',
    parent: 'secured',
    feature: 'dashboard',
    path: 'help',
  },
  secured_dashboard_help_viewer_page: {
    id: 'secured_dashboard_help_viewer_page',
    url: '/secured/dashboard/help/viewer',
    parent: 'secured',
    feature: 'dashboard',
    path: 'help/viewer',
  },
  secured_donation_dashboard_page: {
    id: 'secured_donation_dashboard_page',
    url: '/secured/finance/donations',
    parent: 'secured',
    feature: 'finance',
    path: 'donations',
  },
  secured_report_dashboard_page: {
    id: 'secured_report_dashboard_page',
    url: '/secured/dashboard/reports',
    parent: 'secured',
    feature: 'dashboard',
    path: 'reports',
  },
  secured_donation_bulk_edit_page: {
    id: 'secured_donation_bulk_edit_page',
    url: '/secured/finance/donations/bulk-edit',
    parent: 'secured',
    feature: 'finance',
    path: 'donations/bulk-edit',
  },
  secured_member_members_page: {
    id: 'secured_member_members_page',
    url: '/secured/member/list',
    parent: 'secured',
    feature: 'member',
    path: 'list',
  },
  secured_member_profile_page: {
    id: 'secured_member_profile_page',
    url: '/secured/member', // /:id to be added dynamically
    parent: 'secured',
    feature: 'member',
    path: ':id',
  },
  secured_member_my_profile_page: {
    id: 'secured_member_my_profile_page',
    url: '/secured/member/myprofile',
    parent: 'secured',
    feature: 'member',
    path: 'myprofile',
  },
  secured_member_complete_my_profile_page: {
    id: 'secured_member_complete_my_profile_page',
    url: '/secured/member/completemyprofile',
    parent: 'secured',
    feature: 'member',
    path: 'completemyprofile',
  },
  secured_member_roles_page: {
    id: 'secured_member_roles_page',
    url: '/secured/member/roles',
    parent: 'secured',
    feature: 'member',
    path: 'roles',
  },
  secured_request_list_page: {
    id: 'secured_request_list_page',
    url: '/secured/workflow/requests',
    parent: 'secured',
    feature: 'workflow',
    path: 'requests',
  },
  secured_task_list_page: {
    id: 'secured_task_list_page',
    url: '/secured/workflow/tasks',
    parent: 'secured',
    feature: 'workflow',
    path: 'tasks',
  },
  secured_account_list_page: {
    id: 'secured_account_list_page',
    url: '/secured/finance/accounts',
    parent: 'secured',
    feature: 'finance',
    path: 'accounts',
  },
  secured_manage_account_page: {
    id: 'secured_manage_account_page',
    url: '/secured/finance/expenses',
    parent: 'secured',
    feature: 'finance',
    path: 'expenses',
  },
  secured_account_transaction_page: {
    id: 'secured_account_transaction_page',
    url: '/secured/finance/account/:id/transactions',
    parent: 'secured',
    feature: 'finance',
    path: 'account/:id/transactions',
  },
  secured_notice_notices_page: {
    id: 'secured_notice_notices_page',
    url: '/secured/notice/list',
    parent: 'secured',
    feature: 'notice',
    path: 'list',
  },
  secured_notice_create_page: {
    id: 'secured_notice_create_page',
    url: '/secured/notice/create',
    parent: 'secured',
    feature: 'notice',
    path: 'create',
  },
  secured_notice_update_page: {
    id: 'secured_notice_update_page',
    url: '/secured/notice/:id',
    parent: 'secured',
    feature: 'notice',
    path: ':id',
  },
  secured_admin_dashboard_page: {
    id: 'secured_admin_dashboard_page',
    url: '/secured/admin/dashboard',
    parent: 'secured',
    feature: 'admin',
    path: 'dashboard',
  },
  secured_event_list_page: {
    id: 'secured_event_list_page',
    url: '/secured/socialevents/list',
    parent: 'secured',
    feature: 'socialevents',
    path: 'list'
  },
  secured_project_list_page: {
    id: 'secured_project_list_page',
    url: '/secured/project/list',
    parent: 'secured',
    feature: 'project',
    path: 'list'
  },
  secured_project_activities_page: {
    id: 'secured_project_activities_page',
    url: '/secured/project/:id/activities',
    parent: 'secured',
    feature: 'project',
    path: ':id/activities'
  },
  secured_meetings_list_page: {
    id: 'secured_meetings_list_page',
    url: '/secured/communication/meetings',
    parent: 'secured',
    feature: 'communication',
    path: 'meetings'
  },
};
