/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhoneNumberDto } from '../models/phone-number-dto';
export interface CreateUserDto {
  email: string;
  firstName: string;
  isTemporary: boolean;
  lastName: string;
  phoneNumber: PhoneNumberDto;
}
