/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDonationDto {
  amount: number;

  /**
   * Required in case of ONETIME donations
   */
  donorId?: string;

  /**
   * End date for regular donations
   */
  endDate?: string;

  /**
   * Required in case of ONETIME donations
   */
  forEventId?: string;

  /**
   * Start date for regular donations
   */
  startDate?: string;
  type: 'REGULAR' | 'ONETIME';
}
