/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgendaItemDto } from '../models/agenda-item-dto';
import { MeetingParticipantDto } from '../models/meeting-participant-dto';
export interface MeetingDto {
  agenda?: Array<AgendaItemDto>;
  attendees?: Array<MeetingParticipantDto>;
  calendarLink: string;
  description?: string;
  endTime: string;
  hostEmail?: string;
  id: string;
  location?: string;
  meetLink?: string;
  outcomes?: string;
  startTime: string;
  status: string;
  summary: string;
  type: 'OFFLINE' | 'ONLINE';
}
