/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponseDto {
  actionData?: {
};
  actionType?: string;
  actionUrl?: string;
  archivedAt?: string;
  body: string;
  category: 'SYSTEM' | 'WORKFLOW' | 'DONATION' | 'EXPENSE' | 'PROJECT' | 'MEETING' | 'TASK' | 'DOCUMENT';
  createdAt: string;
  expiresAt?: string;
  icon?: string;
  id: string;
  imageUrl?: string;
  isArchived: boolean;
  isPushSent: boolean;
  isRead: boolean;
  metadata?: {
};
  priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
  pushDelivered: boolean;
  pushSentAt?: string;
  readAt?: string;
  referenceId?: string;
  referenceType?: string;
  title: string;
  type: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'TASK' | 'APPROVAL' | 'REMINDER' | 'ANNOUNCEMENT';
  updatedAt: string;
}
