/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDetailDto } from '../models/account-detail-dto';
export interface SuccessResponseAccountDetailDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: AccountDetailDto;
  timestamp: string;
  traceId: string;
}
