/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuccessResponseArrayString {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: Array<string>;
  timestamp: string;
  traceId: string;
}
