/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StaticDocumentDto } from '../models/static-document-dto';
export interface SuccessResponseArrayStaticDocumentDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: Array<StaticDocumentDto>;
  timestamp: string;
  traceId: string;
}
