/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectDetailDto } from '../models/project-detail-dto';
export interface SuccessResponseProjectDetailDto {
  info: string;
  message: string;

  /**
   * Response payload data
   */
  responsePayload: ProjectDetailDto;
  timestamp: string;
  traceId: string;
}
