/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransferDto {
  amount: number;
  description: string;
  toAccountId: string;
  transferDate: string;
}
