/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDetailDto } from '../models/account-detail-dto';
export interface TransactionDetailDto {
  accBalance?: number;
  accTxnType?: string;
  account?: AccountDetailDto;
  comment?: string;
  transferFrom?: string;
  transferTo?: string;
  txnAmount: number;
  txnDate: string;
  txnDescription: string;
  txnId: string;
  txnNumber?: string;
  txnParticulars?: string;
  txnRefId?: string;
  txnRefType?: 'DONATION' | 'NONE' | 'EXPENSE' | 'EARNING';
  txnStatus: 'SUCCESS' | 'FAILURE' | 'REVERSED';
  txnType: 'IN' | 'OUT' | 'TRANSFER';
}
