/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankDetailDto } from '../models/bank-detail-dto';
import { UpiDetailDto } from '../models/upi-detail-dto';
export interface UpdateAccountSelfDto {
  bankDetail?: BankDetailDto;
  upiDetail?: UpiDetailDto;
}
