/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDonationDto {

  /**
   * Amount
   */
  amount?: number;

  /**
   * Event ID this donation is for
   */
  forEvent?: string;
  isPaymentNotified?: boolean;
  paidOn?: string;

  /**
   * Account ID where payment was made
   */
  paidToAccountId?: string;
  paidUsingUPI?: 'GPAY' | 'PAYTM' | 'PHONEPE' | 'BHARATPAY' | 'UPI_OTH';
  paymentMethod?: 'CASH' | 'NETBANKING' | 'UPI';

  /**
   * Additional remarks
   */
  remarks?: string;
  status?: 'RAISED' | 'PAID' | 'PENDING' | 'PAYMENT_FAILED' | 'PAY_LATER' | 'CANCELLED' | 'UPDATE_MISTAKE';
  transactionRef?: string;
}
