name: 'PR Merged: Release, Deploy to Firebase, Sync Env'
on:
  pull_request:
    paths-ignore:
    - '.github/**'
    types:
      - closed 
    branches:
    - master
    - stage

permissions:
  contents: write      

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}
  
  firebase_deploy:
    if: github.event.pull_request.merged == true
    needs: create_release
    name: Deploy to Firebase
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Firebase-Deploy.yml@main
    with:
     tag_name: ${{ needs.create_release.outputs.tag_name }}
     firebase_project_id: ${{ github.base_ref == 'master' && vars.FIREBASE_PROJECT_ID || vars.FIREBASE_PROJECT_ID_STAGE }}
     npm_run_command: ${{ github.base_ref == 'master' && 'build' || 'buildstage' }}
    secrets:
      firebase_service_account: ${{ github.base_ref == 'master' && secrets.NABARUN_FIREBASE_SERVICE_ACCOUNT || secrets.NABARUN_FIREBASE_SERVICE_ACCOUNT_STAGE }}
  
  auth0_sync:
    if: github.event.pull_request.merged == true && (github.base_ref == 'master' || contains(join(fromJSON(toJSON(github.event.pull_request.labels)).name, ','),'Sync_Auth0'))
    needs: create_release
    name: Sync Auth0 Tenants 
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Auth0-Sync.yml@main
    with:
        branch_name: 'main'
        auth0_source_tenant: ${{ github.base_ref == 'master' && 'STAGE' || 'DEV' }}
        auth0_dest_tenant:  ${{ github.base_ref == 'master' && 'PROD' || 'STAGE' }}
    secrets:
        auth0_secrets: ${{ secrets.AUTH0_CREDENTIALS }}

  run_automated_test:
    if: github.event.pull_request.merged == true && always()
    needs: [firebase_deploy,auth0_sync]
    name: Run Smoke Test 
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Run-Tests.yml@main
    with:
        test_env: ${{ github.base_ref == 'master' && 'prod' || 'stage' }}
        test_doppler_project_name: 'nabarun_test'
        test_cycle: ${{ github.base_ref == 'master' && 'NAB-TR-3' || 'NAB-TR-1' }}
        upload_result: true 
        test_cucumber_tags: ${{ github.base_ref == 'master' && '@smokeprod' || '@smoke' }}
    secrets:
      test_doppler_service_token: ${{ github.base_ref == 'master' && secrets.DOPPLER_TEST_SERVICE_TOKEN || secrets.DOPPLER_TEST_SERVICE_TOKEN_STAGE }}
      qmetry_api_key: ${{ secrets.QMETRY_APIKEY }}
