name: 'PR Merged: Release, Deploy to Firebase, Sync Env'
on:
  pull_request:
    paths-ignore:
    - '.github/**'
    types:
      - closed 
    branches:
    - master
    - stage

permissions:
  contents: write      

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}

  firebase_deploy:
    if: github.event.pull_request.merged == true
    needs: create_release
    runs-on: ubuntu-latest
    name: Trigger Deploy to Firebase
    steps:
       - name: Repository Dispatch
         uses: peter-evans/repository-dispatch@v3
         with:
          token: ${{ secrets.PAT }}
          repository: nabarun-ngo/ngo-nabarun-devops
          event-type: Trigger-Deploy-Sync-Test
          client-payload: |-
              {
                "fe_deploy": "true",
                "fe_tag_name": "${{ needs.create_release.outputs.tag_name }}",
                "target_env": "${{ github.base_ref == 'master' && 'prod' || 'stage' }}",
                "firebase_sync_rc" : "${{ contains(join(fromJSON(toJSON(github.event.pull_request.labels)).name, ','),'auth0') }}",
                "run_smoke_test" : "true"
              }
