name: 'PR Merged: Release, Deploy to Firebase, Sync Env'
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - '.github/**'
    types: [opened, synchronize, reopened, closed] 
    branches:
    - master
    - stage

permissions:
  contents: write      

jobs:
  build:
   name: Build and Test Angular Application
   uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Build-Test.yml@main
   with:
      platform: "node"
      command: "npm install && npm run ${{ github.base_ref == 'master' && 'build' || 'build:stage' }}"
      
  create_release:
    if: github.event.pull_request.merged == true
    needs: build
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}

  firebase_deploy:
    if: github.event.pull_request.merged == true
    needs: create_release
    name: Trigger Deploy to Firebase
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Trigger-Workflow.yml@main    
    with:
      repository: 'nabarun-ngo/ngo-nabarun-ops' 
      event_type: Trigger-DeployFE-Sync-Test
      input_json: |-
        {
          "fe_deploy": true,
          "fe_tag_name": "${{ needs.create_release.outputs.tag_name }}",
          "target_env": "${{ github.base_ref == 'master' && 'prod' || 'stage' }}",
          "auth0_sync" : ${{ contains(join(fromJSON(toJSON(github.event.pull_request.labels)).name, ','),'auth0') }},
          "run_smoke_test" : true ,
          "pr_number": "PR#${{github.event.pull_request.number}}"
        }
    secrets:
      token: ${{ secrets.PAT }}
