/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateGuestDonationDto } from '../../models/create-guest-donation-dto';
import { SuccessResponseDonationDto } from '../../models/success-response-donation-dto';

export interface CreateGuestDonation$Params {
      body: CreateGuestDonationDto
}

export function createGuestDonation(http: HttpClient, rootUrl: string, params: CreateGuestDonation$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseDonationDto>> {
  const rb = new RequestBuilder(rootUrl, createGuestDonation.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseDonationDto>;
    })
  );
}

createGuestDonation.PATH = '/api/donation/create/guest';
