/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseItemDetail } from '../../models/expense-item-detail';
import { SuccessResponseExpenseItemDetail } from '../../models/success-response-expense-item-detail';

export interface CreateExpenseItem$Params {
  id: string;
  'Correlation-Id'?: string;
      body: ExpenseItemDetail
}

export function createExpenseItem(http: HttpClient, rootUrl: string, params: CreateExpenseItem$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponseExpenseItemDetail>> {
  const rb = new RequestBuilder(rootUrl, createExpenseItem.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('Correlation-Id', params['Correlation-Id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponseExpenseItemDetail>;
    })
  );
}

createExpenseItem.PATH = '/api/account/expense/{id}/createitem';
