/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponsePaginateTransactionDetail } from '../../models/success-response-paginate-transaction-detail';
import { TransactionDetailFilter } from '../../models/transaction-detail-filter';

export interface GetMyTransactions$Params {
  id: string;
  pageIndex?: number;
  pageSize?: number;
  filter: TransactionDetailFilter;
  'Correlation-Id'?: string;
}

export function getMyTransactions(http: HttpClient, rootUrl: string, params: GetMyTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponsePaginateTransactionDetail>> {
  const rb = new RequestBuilder(rootUrl, getMyTransactions.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('filter', params.filter, {});
    rb.header('Correlation-Id', params['Correlation-Id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponsePaginateTransactionDetail>;
    })
  );
}

getMyTransactions.PATH = '/api/account/{id}/getMyTransactions';
